[01: 37: 42]: {
    'AuxData': 0,
    'Body': < CharCtrlComponent object at 0x6dd4ce6300 > ,
    'Distance': 9.930063247680664,
    'Flags': 7,
    'IsHit': True,
    'MaterialTypeId': 0,
    'Normal': < -0.3328,
    0.7080,
    0.6229 > ,
    'Pos': < -8.9479,
    1.5802,
    -13.2231 > ,
    'Shape': < PhysicsShapeInstance object at 0x6dd4cd02c0 > ,
    '__class__': < class 'CollisionResult' > ,
    '__delattr__': < method - wrapper '__delattr__' of CollisionResult object at 0x6dd4cd1540 > ,
    '__dict__': {},
    '__dir__': < built - in method __dir__ of CollisionResult object at 0x6dd4cd1540 > ,
    '__doc__': 'CollisionResult',
    '__eq__': < method - wrapper '__eq__' of CollisionResult object at 0x6dd4cd1540 > ,
    '__format__': < built - in method __format__ of CollisionResult object at 0x6dd4cd1540 > ,
    '__ge__': < method - wrapper '__ge__' of CollisionResult object at 0x6dd4cd1540 > ,
    '__getattribute__': < method - wrapper '__getattribute__' of CollisionResult object at 0x6dd4cd1540 > ,
    '__getstate__': < built - in method __getstate__ of CollisionResult object at 0x6dd4cd1540 > ,
    '__gt__': < method - wrapper '__gt__' of CollisionResult object at 0x6dd4cd1540 > ,
    '__hash__': < method - wrapper '__hash__' of CollisionResult object at 0x6dd4cd1540 > ,
    '__init__': < method - wrapper '__init__' of CollisionResult object at 0x6dd4cd1540 > ,
    '__init_subclass__': < built - in method __init_subclass__ of type object at 0x6eaae031d0 > ,
    '__le__': < method - wrapper '__le__' of CollisionResult object at 0x6dd4cd1540 > ,
    '__lt__': < method - wrapper '__lt__' of CollisionResult object at 0x6dd4cd1540 > ,
    '__ne__': < method - wrapper '__ne__' of CollisionResult object at 0x6dd4cd1540 > ,
    '__new__': < built - in method __new__ of type object at 0x6eaae031d0 > ,
    '__reduce__': < built - in method __reduce__ of CollisionResult object at 0x6dd4cd1540 > ,
    '__reduce_ex__': < built - in method __reduce_ex__ of CollisionResult object at 0x6dd4cd1540 > ,
    '__repr__': < method - wrapper '__repr__' of CollisionResult object at 0x6dd4cd1540 > ,
    '__setattr__': < method - wrapper '__setattr__' of CollisionResult object at 0x6dd4cd1540 > ,
    '__sizeof__': < built - in method __sizeof__ of CollisionResult object at 0x6dd4cd1540 > ,
    '__str__': < method - wrapper '__str__' of CollisionResult object at 0x6dd4cd1540 > ,
    '__subclasshook__': < built - in method __subclasshook__ of type object at 0x6eaae031d0 > ,
    '__weakref__': None
}