{
    '__class__': < class 'gclient.util.gun_skin_util.GunSkinDefaultItem' > ,
    '__delattr__': < method - wrapper '__delattr__' of GunSkinDefaultItem object at 0x780f2d0e90 > ,
    '__dict__': {
        'guid': '',
        'gun_id': 10,
        'is_guise': True,
        'is_skin': False,
        'equip_id': 40,
        'item_id': 0,
        'item_proto': {
            'icon': 345,
            'quality': 1
        },
        'skin_id': None,
        'guise_id': None,
        'skin_optic_id': None,
        'skin_optic_part_id': None,
        'expire_time': 0,
        'is_origin_item': True,
        'is_random_item': False
    },
    '__dir__': < built - in method __dir__ of GunSkinDefaultItem object at 0x780f2d0e90 > ,
    '__doc__': None,
    '__eq__': < method - wrapper '__eq__' of GunSkinDefaultItem object at 0x780f2d0e90 > ,
    '__format__': < built - in method __format__ of GunSkinDefaultItem object at 0x780f2d0e90 > ,
    '__ge__': < method - wrapper '__ge__' of GunSkinDefaultItem object at 0x780f2d0e90 > ,
    '__getattribute__': < method - wrapper '__getattribute__' of GunSkinDefaultItem object at 0x780f2d0e90 > ,
    '__getstate__': < built - in method __getstate__ of GunSkinDefaultItem object at 0x780f2d0e90 > ,
    '__gt__': < method - wrapper '__gt__' of GunSkinDefaultItem object at 0x780f2d0e90 > ,
    '__hash__': < method - wrapper '__hash__' of GunSkinDefaultItem object at 0x780f2d0e90 > ,
    '__init__': < bound method GunSkinDefaultItem.__init__ of < gclient.util.gun_skin_util.GunSkinDefaultItem object at 0x780f2d0e90 >> ,
    '__init_subclass__': < built - in method __init_subclass__ of type object at 0x78263d8410 > ,
    '__le__': < method - wrapper '__le__' of GunSkinDefaultItem object at 0x780f2d0e90 > ,
    '__lt__': < method - wrapper '__lt__' of GunSkinDefaultItem object at 0x780f2d0e90 > ,
    '__module__': 'gclient.util.gun_skin_util',
    '__ne__': < method - wrapper '__ne__' of GunSkinDefaultItem object at 0x780f2d0e90 > ,
    '__new__': < built - in method __new__ of type object at 0x78d45030a8 > ,
    '__reduce__': < built - in method __reduce__ of GunSkinDefaultItem object at 0x780f2d0e90 > ,
    '__reduce_ex__': < built - in method __reduce_ex__ of GunSkinDefaultItem object at 0x780f2d0e90 > ,
    '__repr__': < method - wrapper '__repr__' of GunSkinDefaultItem object at 0x780f2d0e90 > ,
    '__setattr__': < method - wrapper '__setattr__' of GunSkinDefaultItem object at 0x780f2d0e90 > ,
    '__sizeof__': < built - in method __sizeof__ of GunSkinDefaultItem object at 0x780f2d0e90 > ,
    '__str__': < method - wrapper '__str__' of GunSkinDefaultItem object at 0x780f2d0e90 > ,
    '__subclasshook__': < built - in method __subclasshook__ of type object at 0x78263d8410 > ,
    '__weakref__': None,
    'equip_id': 40,
    'expire_time': 0,
    'guid': '',
    'guise_id': None,
    'gun_id': 10,
    'is_guise': True,
    'is_origin_item': True,
    'is_random_item': False,
    'is_skin': False,
    'item_id': 0,
    'item_proto': {
        'icon': 345,
        'quality': 1
    },
    'skin_id': None,
    'skin_optic_id': None,
    'skin_optic_part_id': None
}