{
    'Action': None,
    'Anchor': < 0,
    0,
    0 > ,
    'AnimatorDestructor': None,
    'Appearance': None,
    'Area': None,
    'Audio': None,
    'AudioObject': None,
    'Billboard': None,
    'BillboardLockY': True,
    'Blurriness': 1.0,
    'CharCtrl': None,
    'ClothSimulator': None,
    'Constraints': [],
    'Decal': None,
    'DeprecatedBit1': False,
    'Destruct': None,
    'DetailLevel': 0,
    'DockingMark': None,
    'EnableDepthOfField': False,
    'EnvVolume': None,
    'Fading': 0.0,
    'Far': 1000.0,
    'FarTransitionRegion': 50.0,
    'FieldOfView': 50.0,
    'Filter': None,
    'FocalDistance': 0.0,
    'FocalRegion': 50.0,
    'Heightmap': None,
    'InSkyBoxDistance': 100.0,
    'InSkyBoxPitch': 0.0,
    'InSkyBoxYaw': 0.0,
    'InheritVirtualColor': False,
    'IsAnimated': False,
    'IsBillboard': False,
    'IsCastDynamicShadow': False,
    'IsDisableCollision': False,
    'IsDisableFakeCmd': False,
    'IsDissolving': False,
    'IsInSkyBox': False,
    'IsInWorld': False,
    'IsLevelProxy': False,
    'IsMovable': False,
    'IsOrthographic': False,
    'IsOutlined': False,
    'IsOverrideLodThreshold': False,
    'IsPointCloudLight': True,
    'IsReadyToAppear': True,
    'IsReceiveDynamicShadow': True,
    'IsReflectionVisible': True,
    'IsRenderStateChanged': False,
    'IsResourceReady': False,
    'IsSDFGen': True,
    'IsVisible': True,
    'IsWarmingUp': False,
    'IsWholeLevelVisible': True,
    'Level': None,
    'LevelProxy': None,
    'Light': None,
    'LightProbe': None,
    'LoadResourceExtend': 0.0,
    'LodThreshold': < 0.0000,
    0.0000,
    0.0000 > ,
    'NavigateGadget': None,
    'NavigateObstacle': None,
    'Near': 0.10000000149011612,
    'NearTransitionRegion': 0.0,
    'OrthoScale': 1.0,
    'PointCloud': None,
    'PoseSender': None,
    'Primitives': [],
    'Ragdoll': None,
    'ReflectionProbe': None,
    'RigidBodies': [],
    'SHVolume': None,
    'SceneGuider': None,
    'ShaderGraphOverrideMaterialInfo': [],
    'Skeleton': None,
    'SnowTrail': None,
    'Storyboard': None,
    'Tach': < TachComponent object at 0x78017d03c0 > ,
    'Tag': None,
    'TechParam': < 0.0000,
    0.0000,
    0.0000 > ,
    'TechParam2': < 0.0000,
    0.0000,
    0.0000,
    0.0000 > ,
    'TechState': 0,
    'TintColor1': < 1.0000,
    1.0000,
    1.0000 > ,
    'TintColor2': < 1.0000,
    1.0000,
    1.0000 > ,
    'TintColor3': < 1.0000,
    1.0000,
    1.0000 > ,
    'Token': 0,
    'Transform': << -0.6946,
    0.0000,
    0.7194 > < 0.1410,
    0.9806,
    0.1361 > < -0.7055,
    0.1959,
    -0.6811 > < -16.5372,
    1.5435,
    -6.7032 >> ,
    'TransformUpdate': None,
    'UI': None,
    'ViewMatrix': << -0.6946,
    0.1410,
    -0.7055 > < 0.0000,
    0.9806,
    0.1959 > < 0.7194,
    0.1361,
    -0.6811 > < -6.6645,
    1.7296,
    -16.5344 >> ,
    'VirtualCameraManager': < VirtualCameraManager object at 0x78017ebe00 > ,
    'VisibilityCube': None,
    'Volume': None,
    'World': None,
    '__class__': < class 'ICamera' > ,
    '__dict__': {},
    '__doc__': 'ICamera',
    '__weakref__': None
}