[09: 48: 44]: {
    'INIT': '0e6113d4ce4eff879210bd2b4cb3e06c',
    '__class__': < class 'MImporter.finder' > ,
    '__delattr__': < method - wrapper '__delattr__' of finder object at 0x7b6ccfd510 > ,
    '__dict__': {
        '_relpath_cache': {
            '/storage/emulated/0/Android/data/com.netease.newspikeme/files/Package/Script/Python': '',
            '/storage/emulated/0/Android/data/com.netease.newspikeme/files/Package/Script/Python/Lib3': 'Lib3/',
            '/storage/emulated/0/Android/data/com.netease.newspikeme/files/Package/Script/Python/Lib3/collections': 'Lib3/collections/',
            '/storage/emulated/0/Android/data/com.netease.newspikeme/files/Package/Script/Python/Lib3/re': 'Lib3/re/',
            '/storage/emulated/0/Android/data/com.netease.newspikeme/files/Package/Script/Python/Lib3/importlib': 'Lib3/importlib/',
            '/storage/emulated/0/Android/data/com.netease.newspikeme/files/Package/Script/Python/Lib3/json': 'Lib3/json/',
            '/storage/emulated/0/Android/data/com.netease.newspikeme/files/Package/Script/Python/pydetect': 'pydetect/',
            '/storage/emulated/0/Android/data/com.netease.newspikeme/files/Package/Script/Python/Lib3/http': 'Lib3/http/',
            '/storage/emulated/0/Android/data/com.netease.newspikeme/files/Package/Script/Python/Lib3/email': 'Lib3/email/',
            '/storage/emulated/0/Android/data/com.netease.newspikeme/files/Package/Script/Python/Lib3/urllib': 'Lib3/urllib/',
            '/storage/emulated/0/Android/data/com.netease.newspikeme/files/Package/Script/Python/engine': 'engine/',
            '/storage/emulated/0/Android/data/com.netease.newspikeme/files/Package/Script/Python/engine/Lib': 'engine/Lib/',
            '/storage/emulated/0/Android/data/com.netease.newspikeme/files/Package/Script/Python/Montage': 'Montage/',
            '/storage/emulated/0/Android/data/com.netease.newspikeme/files/Package/Script/Python/HelenFramework': 'HelenFramework/',
            '/storage/emulated/0/Android/data/com.netease.newspikeme/files/Package/Script/Python/char_editor2': 'char_editor2/',
            '/storage/emulated/0/Android/data/com.netease.newspikeme/files/Package/Script/Python/char_editor2/Common': 'char_editor2/Common/',
            '/storage/emulated/0/Android/data/com.netease.newspikeme/files/Package/Script/Python/engine/common': 'engine/common/',
            '/storage/emulated/0/Android/data/com.netease.newspikeme/files/Package/Script/Python/engine/mobilelog': 'engine/mobilelog/',
            '/storage/emulated/0/Android/data/com.netease.newspikeme/files/Package/Script/Python/Lib3/logging': 'Lib3/logging/',
            '/storage/emulated/0/Android/data/com.netease.newspikeme/files/Package/Script/Python/gclient': 'gclient/',
            '/storage/emulated/0/Android/data/com.netease.newspikeme/files/Package/Script/Python/gclient/util': 'gclient/util/',
            '/storage/emulated/0/Android/data/com.netease.newspikeme/files/Package/Script/Python/gshare': 'gshare/',
            '/storage/emulated/0/Android/data/com.netease.newspikeme/files/Package/Script/Python/gclient/framework': 'gclient/framework/',
            '/storage/emulated/0/Android/data/com.netease.newspikeme/files/Package/Script/Python/gclient/framework/util': 'gclient/framework/util/',
            '/storage/emulated/0/Android/data/com.netease.newspikeme/files/Package/Script/Python/engine/client': 'engine/client/',
            '/storage/emulated/0/Android/data/com.netease.newspikeme/files/Package/Script/Python/engine/Lib/bson': 'engine/Lib/bson/',
            '/storage/emulated/0/Android/data/com.netease.newspikeme/files/Package/Script/Python/engine/mobilerpc': 'engine/mobilerpc/',
            '/storage/emulated/0/Android/data/com.netease.newspikeme/files/Package/Script/Python/gclient/data': 'gclient/data/',
            '/storage/emulated/0/Android/data/com.netease.newspikeme/files/Package/Script/Python/gclient/gameplay': 'gclient/gameplay/',
            '/storage/emulated/0/Android/data/com.netease.newspikeme/files/Package/Script/Python/gclient/gameplay/util': 'gclient/gameplay/util/',
            '/storage/emulated/0/Android/data/com.netease.newspikeme/files/Package/Script/Python/gclient/util/profile': 'gclient/util/profile/',
            '/storage/emulated/0/Android/data/com.netease.newspikeme/files/Package/Script/Python/gclient/ui': 'gclient/ui/',
            '/storage/emulated/0/Android/data/com.netease.newspikeme/files/Package/Script/Python/gclient/ui/common': 'gclient/ui/common/',
            '/storage/emulated/0/Android/data/com.netease.newspikeme/files/Package/Script/Python/gclient/framework/ui': 'gclient/framework/ui/',
            '/storage/emulated/0/Android/data/com.netease.newspikeme/files/Package/Script/Python/gclient/framework/ui/widgets': 'gclient/framework/ui/widgets/',
            '/storage/emulated/0/Android/data/com.netease.newspikeme/files/Package/Script/Python/gshare/util': 'gshare/util/',
            '/storage/emulated/0/Android/data/com.netease.newspikeme/files/Package/Script/Python/gclient/util/mocks': 'gclient/util/mocks/',
            '/storage/emulated/0/Android/data/com.netease.newspikeme/files/Package/Script/Python/gclient/framework/ui/director_comp': 'gclient/framework/ui/director_comp/',
            '/storage/emulated/0/Android/data/com.netease.newspikeme/files/Package/Script/Python/gclient/local': 'gclient/local/',
            '/storage/emulated/0/Android/data/com.netease.newspikeme/files/Package/Script/Python/gclient/data_lang': 'gclient/data_lang/',
            '/storage/emulated/0/Android/data/com.netease.newspikeme/files/Package/Script/Python/channel': 'channel/',
            '/storage/emulated/0/Android/data/com.netease.newspikeme/files/Package/Script/Python/gshare/const': 'gshare/const/',
            '/storage/emulated/0/Android/data/com.netease.newspikeme/files/Package/Script/Python/gclient/framework/sound': 'gclient/framework/sound/',
            '/storage/emulated/0/Android/data/com.netease.newspikeme/files/Package/Script/Python/gclient/gamesystem': 'gclient/gamesystem/',
            '/storage/emulated/0/Android/data/com.netease.newspikeme/files/Package/Script/Python/gclient/gamesystem/entities': 'gclient/gamesystem/entities/',
            '/storage/emulated/0/Android/data/com.netease.newspikeme/files/Package/Script/Python/gclient/gamesystem/entities/avatarmembers': 'gclient/gamesystem/entities/avatarmembers/',
            '/storage/emulated/0/Android/data/com.netease.newspikeme/files/Package/Script/Python/gclient/data/ets_data': 'gclient/data/ets_data/',
            '/storage/emulated/0/Android/data/com.netease.newspikeme/files/Package/Script/Python/gclient/gameplay/logic_base': 'gclient/gameplay/logic_base/',
            '/storage/emulated/0/Android/data/com.netease.newspikeme/files/Package/Script/Python/gclient/gameplay/logic_base/spell': 'gclient/gameplay/logic_base/spell/',
            '/storage/emulated/0/Android/data/com.netease.newspikeme/files/Package/Script/Python/gclient/gameplay/logic_base/spell/spell_core': 'gclient/gameplay/logic_base/spell/spell_core/',
            '/storage/emulated/0/Android/data/com.netease.newspikeme/files/Package/Script/Python/engine/tools': 'engine/tools/',
            '/storage/emulated/0/Android/data/com.netease.newspikeme/files/Package/Script/Python/gclient/data_lang/data_en': 'gclient/data_lang/data_en/',
            '/storage/emulated/0/Android/data/com.netease.newspikeme/files/Package/Script/Python/gclient/framework/entities': 'gclient/framework/entities/',
            '/storage/emulated/0/Android/data/com.netease.newspikeme/files/Package/Script/Python/gshare/wanster': 'gshare/wanster/',
            '/storage/emulated/0/Android/data/com.netease.newspikeme/files/Package/Script/Python/gclient/framework/entities/avatarmembers': 'gclient/framework/entities/avatarmembers/',
            '/storage/emulated/0/Android/data/com.netease.newspikeme/files/Package/Script/Python/gclient/logic': 'gclient/logic/',
            '/storage/emulated/0/Android/data/com.netease.newspikeme/files/Package/Script/Python/gclient/gamesystem/uihall': 'gclient/gamesystem/uihall/',
            '/storage/emulated/0/Android/data/com.netease.newspikeme/files/Package/Script/Python/gclient/gamesystem/uihall/room': 'gclient/gamesystem/uihall/room/',
            '/storage/emulated/0/Android/data/com.netease.newspikeme/files/Package/Script/Python/gclient/framework/ui/commonnodes': 'gclient/framework/ui/commonnodes/',
            '/storage/emulated/0/Android/data/com.netease.newspikeme/files/Package/Script/Python/gshare/game_logic': 'gshare/game_logic/',
            '/storage/emulated/0/Android/data/com.netease.newspikeme/files/Package/Script/Python/gclient/ui/uilogin': 'gclient/ui/uilogin/',
            '/storage/emulated/0/Android/data/com.netease.newspikeme/files/Package/Script/Python/gclient/gamesystem/uigunsmith': 'gclient/gamesystem/uigunsmith/',
            '/storage/emulated/0/Android/data/com.netease.newspikeme/files/Package/Script/Python/gclient/gamesystem/uihall/gunupgrade': 'gclient/gamesystem/uihall/gunupgrade/',
            '/storage/emulated/0/Android/data/com.netease.newspikeme/files/Package/Script/Python/gclient/gamesystem/uihall/uimall': 'gclient/gamesystem/uihall/uimall/',
            '/storage/emulated/0/Android/data/com.netease.newspikeme/files/Package/Script/Python/gclient/framework/commoncomps': 'gclient/framework/commoncomps/',
            '/storage/emulated/0/Android/data/com.netease.newspikeme/files/Package/Script/Python/gclient/gameplay/logic_rookieguide': 'gclient/gameplay/logic_rookieguide/',
            '/storage/emulated/0/Android/data/com.netease.newspikeme/files/Package/Script/Python/gclient/gameplay/logic_rookieguide/ui': 'gclient/gameplay/logic_rookieguide/ui/',
            '/storage/emulated/0/Android/data/com.netease.newspikeme/files/Package/Script/Python/gclient/gameplay/uicomponents': 'gclient/gameplay/uicomponents/',
            '/storage/emulated/0/Android/data/com.netease.newspikeme/files/Package/Script/Python/gclient/util/iconbake': 'gclient/util/iconbake/',
            '/storage/emulated/0/Android/data/com.netease.newspikeme/files/Package/Script/Python/gclient/gameplay/logic_base/equips': 'gclient/gameplay/logic_base/equips/',
            '/storage/emulated/0/Android/data/com.netease.newspikeme/files/Package/Script/Python/gclient/gameplay/logic_base/models': 'gclient/gameplay/logic_base/models/',
            '/storage/emulated/0/Android/data/com.netease.newspikeme/files/Package/Script/Python/gclient/framework/models': 'gclient/framework/models/',
            '/storage/emulated/0/Android/data/com.netease.newspikeme/files/Package/Script/Python/gclient/util/cinematics': 'gclient/util/cinematics/',
            '/storage/emulated/0/Android/data/com.netease.newspikeme/files/Package/Script/Python/SunshineSDK': 'SunshineSDK/',
            '/storage/emulated/0/Android/data/com.netease.newspikeme/files/Package/Script/Python/SunshineSDK/Custom': 'SunshineSDK/Custom/',
            '/storage/emulated/0/Android/data/com.netease.newspikeme/files/Package/Script/Python/SunshineSDK/Meta': 'SunshineSDK/Meta/',
            '/storage/emulated/0/Android/data/com.netease.newspikeme/files/Package/Script/Python/gclient/gameplay/logic_base/ui': 'gclient/gameplay/logic_base/ui/',
            '/storage/emulated/0/Android/data/com.netease.newspikeme/files/Package/Script/Python/gclient/gameplay/logic_moba_zombie': 'gclient/gameplay/logic_moba_zombie/',
            '/storage/emulated/0/Android/data/com.netease.newspikeme/files/Package/Script/Python/gclient/gameplay/logic_moba_zombie/ui': 'gclient/gameplay/logic_moba_zombie/ui/',
            '/storage/emulated/0/Android/data/com.netease.newspikeme/files/Package/Script/Python/gclient/gamesystem/models': 'gclient/gamesystem/models/',
            '/storage/emulated/0/Android/data/com.netease.newspikeme/files/Package/Script/Python/gclient/gamesystem/uihall/game_map_choose': 'gclient/gamesystem/uihall/game_map_choose/',
            '/storage/emulated/0/Android/data/com.netease.newspikeme/files/Package/Script/Python/gclient/gamesystem/uihall/chat': 'gclient/gamesystem/uihall/chat/',
            '/storage/emulated/0/Android/data/com.netease.newspikeme/files/Package/Script/Python/gclient/gamesystem/uihall/clan': 'gclient/gamesystem/uihall/clan/',
            '/storage/emulated/0/Android/data/com.netease.newspikeme/files/Package/Script/Python/gclient/gamesystem/uihall/clan/util': 'gclient/gamesystem/uihall/clan/util/',
            '/storage/emulated/0/Android/data/com.netease.newspikeme/files/Package/Script/Python/gclient/gamesystem/uihall/clan/components': 'gclient/gamesystem/uihall/clan/components/',
            '/storage/emulated/0/Android/data/com.netease.newspikeme/files/Package/Script/Python/gclient/framework/camera': 'gclient/framework/camera/',
            '/storage/emulated/0/Android/data/com.netease.newspikeme/files/Package/Script/Python/SunshineSDK/Custom/Editor': 'SunshineSDK/Custom/Editor/',
            '/storage/emulated/0/Android/data/com.netease.newspikeme/files/Package/Script/Python/SunshineSDK/Custom/Editor/EditorMeta': 'SunshineSDK/Custom/Editor/EditorMeta/',
            '/storage/emulated/0/Android/data/com.netease.newspikeme/files/Package/Script/Python/SunshineSDK/Custom/Editor/EditorMeta/camera': 'SunshineSDK/Custom/Editor/EditorMeta/camera/',
            '/storage/emulated/0/Android/data/com.netease.newspikeme/files/Package/Script/Python/SunshineSDK/Custom/Editor/EditorMeta/weapon': 'SunshineSDK/Custom/Editor/EditorMeta/weapon/',
            '/storage/emulated/0/Android/data/com.netease.newspikeme/files/Package/Script/Python/SunshineSDK/Custom/Editor/EditorMeta/vehicle': 'SunshineSDK/Custom/Editor/EditorMeta/vehicle/',
            '/storage/emulated/0/Android/data/com.netease.newspikeme/files/Package/Script/Python/SunshineSDK/Custom/Entity': 'SunshineSDK/Custom/Entity/',
            '/storage/emulated/0/Android/data/com.netease.newspikeme/files/Package/Script/Python/SunshineSDK/Custom/Entity/Vehicle': 'SunshineSDK/Custom/Entity/Vehicle/',
            '/storage/emulated/0/Android/data/com.netease.newspikeme/files/Package/Script/Python/gclient/data/ets_data/camera': 'gclient/data/ets_data/camera/',
            '/storage/emulated/0/Android/data/com.netease.newspikeme/files/Package/Script/Python/gclient/gamesystem/entities/avatarmembers/activity_data_cls': 'gclient/gamesystem/entities/avatarmembers/activity_data_cls/',
            '/storage/emulated/0/Android/data/com.netease.newspikeme/files/Package/Script/Python/gshare/activity_data': 'gshare/activity_data/',
            '/storage/emulated/0/Android/data/com.netease.newspikeme/files/Package/Script/Python/gclient/gamesystem/uisettingnew': 'gclient/gamesystem/uisettingnew/',
            '/storage/emulated/0/Android/data/com.netease.newspikeme/files/Package/Script/Python/gclient/gameplay/logic_shootingrange': 'gclient/gameplay/logic_shootingrange/',
            '/storage/emulated/0/Android/data/com.netease.newspikeme/files/Package/Script/Python/gclient/gameplay/logic_shootingrange/ui': 'gclient/gameplay/logic_shootingrange/ui/',
            '/storage/emulated/0/Android/data/com.netease.newspikeme/files/Package/Script/Python/gclient/gamesystem/uihall/uipass': 'gclient/gamesystem/uihall/uipass/',
            '/storage/emulated/0/Android/data/com.netease.newspikeme/files/Package/Script/Python/gclient/gamesystem/uihero': 'gclient/gamesystem/uihero/',
            '/storage/emulated/0/Android/data/com.netease.newspikeme/files/Package/Script/Python/gclient/gamesystem/uiwarehouse': 'gclient/gamesystem/uiwarehouse/',
            '/storage/emulated/0/Android/data/com.netease.newspikeme/files/Package/Script/Python/gclient/gameplay/logic_moba': 'gclient/gameplay/logic_moba/',
            '/storage/emulated/0/Android/data/com.netease.newspikeme/files/Package/Script/Python/gclient/gameplay/logic_moba/ui': 'gclient/gameplay/logic_moba/ui/',
            '/storage/emulated/0/Android/data/com.netease.newspikeme/files/Package/Script/Python/gclient/gamesystem/uihall/uicalculation': 'gclient/gamesystem/uihall/uicalculation/',
            '/storage/emulated/0/Android/data/com.netease.newspikeme/files/Package/Script/Python/gclient/gamesystem/uihall/activity': 'gclient/gamesystem/uihall/activity/',
            '/storage/emulated/0/Android/data/com.netease.newspikeme/files/Package/Script/Python/gclient/gamesystem/uihall/activity/halloween': 'gclient/gamesystem/uihall/activity/halloween/',
            '/storage/emulated/0/Android/data/com.netease.newspikeme/files/Package/Script/Python/gclient/gamesystem/uihall/ui_personal_space': 'gclient/gamesystem/uihall/ui_personal_space/',
            '/storage/emulated/0/Android/data/com.netease.newspikeme/files/Package/Script/Python/gclient/gamesystem/uihall/activity/yearly_review': 'gclient/gamesystem/uihall/activity/yearly_review/',
            '/storage/emulated/0/Android/data/com.netease.newspikeme/files/Package/Script/Python/gclient/gameplay/logic_base/entities': 'gclient/gameplay/logic_base/entities/',
            '/storage/emulated/0/Android/data/com.netease.newspikeme/files/Package/Script/Python/gclient/gameplay/logic_base/comps': 'gclient/gameplay/logic_base/comps/',
            '/storage/emulated/0/Android/data/com.netease.newspikeme/files/Package/Script/Python/gclient/gameplay/logic_moba_first': 'gclient/gameplay/logic_moba_first/',
            '/storage/emulated/0/Android/data/com.netease.newspikeme/files/Package/Script/Python/gclient/gameplay/logic_moba_first/ui': 'gclient/gameplay/logic_moba_first/ui/',
            '/storage/emulated/0/Android/data/com.netease.newspikeme/files/Package/Script/Python/gclient/gameplay/logic_base/entities/combatavatarmembers': 'gclient/gameplay/logic_base/entities/combatavatarmembers/',
            '/storage/emulated/0/Android/data/com.netease.newspikeme/files/Package/Script/Python/gclient/gameplay/logic_base/bot': 'gclient/gameplay/logic_base/bot/',
            '/storage/emulated/0/Android/data/com.netease.newspikeme/files/Package/Script/Python/gshare/bot': 'gshare/bot/',
            '/storage/emulated/0/Android/data/com.netease.newspikeme/files/Package/Script/Python/HelenFramework/HelenAI': 'HelenFramework/HelenAI/',
            '/storage/emulated/0/Android/data/com.netease.newspikeme/files/Package/Script/Python/HelenFramework/HelenAI/ai_consts': 'HelenFramework/HelenAI/ai_consts/',
            '/storage/emulated/0/Android/data/com.netease.newspikeme/files/Package/Script/Python/gclient/gameplay/logic_base/entities/robotcomponents': 'gclient/gameplay/logic_base/entities/robotcomponents/'
        }
    },
    '__dir__': < built - in method __dir__ of finder object at 0x7b6ccfd510 > ,
    '__doc__': None,
    '__eq__': < method - wrapper '__eq__' of finder object at 0x7b6ccfd510 > ,
    '__format__': < built - in method __format__ of finder object at 0x7b6ccfd510 > ,
    '__ge__': < method - wrapper '__ge__' of finder object at 0x7b6ccfd510 > ,
    '__getattribute__': < method - wrapper '__getattribute__' of finder object at 0x7b6ccfd510 > ,
    '__getstate__': < built - in method __getstate__ of finder object at 0x7b6ccfd510 > ,
    '__gt__': < method - wrapper '__gt__' of finder object at 0x7b6ccfd510 > ,
    '__hash__': < method - wrapper '__hash__' of finder object at 0x7b6ccfd510 > ,
    '__init__': < bound method finder.__init__ of < MImporter.finder object at 0x7b6ccfd510 >> ,
    '__init_subclass__': < built - in method __init_subclass__ of type object at 0x7b4f16d810 > ,
    '__le__': < method - wrapper '__le__' of finder object at 0x7b6ccfd510 > ,
    '__lt__': < method - wrapper '__lt__' of finder object at 0x7b6ccfd510 > ,
    '__module__': 'MImporter',
    '__ne__': < method - wrapper '__ne__' of finder object at 0x7b6ccfd510 > ,
    '__new__': < built - in method __new__ of type object at 0x7b8fc710a8 > ,
    '__reduce__': < built - in method __reduce__ of finder object at 0x7b6ccfd510 > ,
    '__reduce_ex__': < built - in method __reduce_ex__ of finder object at 0x7b6ccfd510 > ,
    '__repr__': < method - wrapper '__repr__' of finder object at 0x7b6ccfd510 > ,
    '__setattr__': < method - wrapper '__setattr__' of finder object at 0x7b6ccfd510 > ,
    '__sizeof__': < built - in method __sizeof__ of finder object at 0x7b6ccfd510 > ,
    '__str__': < method - wrapper '__str__' of finder object at 0x7b6ccfd510 > ,
    '__subclasshook__': < built - in method __subclasshook__ of type object at 0x7b4f16d810 > ,
    '__weakref__': None,
    '_create_module': < bound method finder._create_module of < MImporter.finder object at 0x7b6ccfd510 >> ,
    '_get_relpath': < bound method finder._get_relpath of < MImporter.finder object at 0x7b6ccfd510 >> ,
    '_import_module': < bound method finder._import_module of < MImporter.finder object at 0x7b6ccfd510 >> ,
    '_lazy_import_module': < bound method finder._lazy_import_module of < MImporter.finder object at 0x7b6ccfd510 >> ,
    '_load_encrypted_module': < bound method finder._load_encrypted_module of < MImporter.finder object at 0x7b6ccfd510 >> ,
    '_relpath_cache': {
        '/storage/emulated/0/Android/data/com.netease.newspikeme/files/Package/Script/Python': '',
        '/storage/emulated/0/Android/data/com.netease.newspikeme/files/Package/Script/Python/Lib3': 'Lib3/',
        '/storage/emulated/0/Android/data/com.netease.newspikeme/files/Package/Script/Python/Lib3/collections': 'Lib3/collections/',
        '/storage/emulated/0/Android/data/com.netease.newspikeme/files/Package/Script/Python/Lib3/re': 'Lib3/re/',
        '/storage/emulated/0/Android/data/com.netease.newspikeme/files/Package/Script/Python/Lib3/importlib': 'Lib3/importlib/',
        '/storage/emulated/0/Android/data/com.netease.newspikeme/files/Package/Script/Python/Lib3/json': 'Lib3/json/',
        '/storage/emulated/0/Android/data/com.netease.newspikeme/files/Package/Script/Python/pydetect': 'pydetect/',
        '/storage/emulated/0/Android/data/com.netease.newspikeme/files/Package/Script/Python/Lib3/http': 'Lib3/http/',
        '/storage/emulated/0/Android/data/com.netease.newspikeme/files/Package/Script/Python/Lib3/email': 'Lib3/email/',
        '/storage/emulated/0/Android/data/com.netease.newspikeme/files/Package/Script/Python/Lib3/urllib': 'Lib3/urllib/',
        '/storage/emulated/0/Android/data/com.netease.newspikeme/files/Package/Script/Python/engine': 'engine/',
        '/storage/emulated/0/Android/data/com.netease.newspikeme/files/Package/Script/Python/engine/Lib': 'engine/Lib/',
        '/storage/emulated/0/Android/data/com.netease.newspikeme/files/Package/Script/Python/Montage': 'Montage/',
        '/storage/emulated/0/Android/data/com.netease.newspikeme/files/Package/Script/Python/HelenFramework': 'HelenFramework/',
        '/storage/emulated/0/Android/data/com.netease.newspikeme/files/Package/Script/Python/char_editor2': 'char_editor2/',
        '/storage/emulated/0/Android/data/com.netease.newspikeme/files/Package/Script/Python/char_editor2/Common': 'char_editor2/Common/',
        '/storage/emulated/0/Android/data/com.netease.newspikeme/files/Package/Script/Python/engine/common': 'engine/common/',
        '/storage/emulated/0/Android/data/com.netease.newspikeme/files/Package/Script/Python/engine/mobilelog': 'engine/mobilelog/',
        '/storage/emulated/0/Android/data/com.netease.newspikeme/files/Package/Script/Python/Lib3/logging': 'Lib3/logging/',
        '/storage/emulated/0/Android/data/com.netease.newspikeme/files/Package/Script/Python/gclient': 'gclient/',
        '/storage/emulated/0/Android/data/com.netease.newspikeme/files/Package/Script/Python/gclient/util': 'gclient/util/',
        '/storage/emulated/0/Android/data/com.netease.newspikeme/files/Package/Script/Python/gshare': 'gshare/',
        '/storage/emulated/0/Android/data/com.netease.newspikeme/files/Package/Script/Python/gclient/framework': 'gclient/framework/',
        '/storage/emulated/0/Android/data/com.netease.newspikeme/files/Package/Script/Python/gclient/framework/util': 'gclient/framework/util/',
        '/storage/emulated/0/Android/data/com.netease.newspikeme/files/Package/Script/Python/engine/client': 'engine/client/',
        '/storage/emulated/0/Android/data/com.netease.newspikeme/files/Package/Script/Python/engine/Lib/bson': 'engine/Lib/bson/',
        '/storage/emulated/0/Android/data/com.netease.newspikeme/files/Package/Script/Python/engine/mobilerpc': 'engine/mobilerpc/',
        '/storage/emulated/0/Android/data/com.netease.newspikeme/files/Package/Script/Python/gclient/data': 'gclient/data/',
        '/storage/emulated/0/Android/data/com.netease.newspikeme/files/Package/Script/Python/gclient/gameplay': 'gclient/gameplay/',
        '/storage/emulated/0/Android/data/com.netease.newspikeme/files/Package/Script/Python/gclient/gameplay/util': 'gclient/gameplay/util/',
        '/storage/emulated/0/Android/data/com.netease.newspikeme/files/Package/Script/Python/gclient/util/profile': 'gclient/util/profile/',
        '/storage/emulated/0/Android/data/com.netease.newspikeme/files/Package/Script/Python/gclient/ui': 'gclient/ui/',
        '/storage/emulated/0/Android/data/com.netease.newspikeme/files/Package/Script/Python/gclient/ui/common': 'gclient/ui/common/',
        '/storage/emulated/0/Android/data/com.netease.newspikeme/files/Package/Script/Python/gclient/framework/ui': 'gclient/framework/ui/',
        '/storage/emulated/0/Android/data/com.netease.newspikeme/files/Package/Script/Python/gclient/framework/ui/widgets': 'gclient/framework/ui/widgets/',
        '/storage/emulated/0/Android/data/com.netease.newspikeme/files/Package/Script/Python/gshare/util': 'gshare/util/',
        '/storage/emulated/0/Android/data/com.netease.newspikeme/files/Package/Script/Python/gclient/util/mocks': 'gclient/util/mocks/',
        '/storage/emulated/0/Android/data/com.netease.newspikeme/files/Package/Script/Python/gclient/framework/ui/director_comp': 'gclient/framework/ui/director_comp/',
        '/storage/emulated/0/Android/data/com.netease.newspikeme/files/Package/Script/Python/gclient/local': 'gclient/local/',
        '/storage/emulated/0/Android/data/com.netease.newspikeme/files/Package/Script/Python/gclient/data_lang': 'gclient/data_lang/',
        '/storage/emulated/0/Android/data/com.netease.newspikeme/files/Package/Script/Python/channel': 'channel/',
        '/storage/emulated/0/Android/data/com.netease.newspikeme/files/Package/Script/Python/gshare/const': 'gshare/const/',
        '/storage/emulated/0/Android/data/com.netease.newspikeme/files/Package/Script/Python/gclient/framework/sound': 'gclient/framework/sound/',
        '/storage/emulated/0/Android/data/com.netease.newspikeme/files/Package/Script/Python/gclient/gamesystem': 'gclient/gamesystem/',
        '/storage/emulated/0/Android/data/com.netease.newspikeme/files/Package/Script/Python/gclient/gamesystem/entities': 'gclient/gamesystem/entities/',
        '/storage/emulated/0/Android/data/com.netease.newspikeme/files/Package/Script/Python/gclient/gamesystem/entities/avatarmembers': 'gclient/gamesystem/entities/avatarmembers/',
        '/storage/emulated/0/Android/data/com.netease.newspikeme/files/Package/Script/Python/gclient/data/ets_data': 'gclient/data/ets_data/',
        '/storage/emulated/0/Android/data/com.netease.newspikeme/files/Package/Script/Python/gclient/gameplay/logic_base': 'gclient/gameplay/logic_base/',
        '/storage/emulated/0/Android/data/com.netease.newspikeme/files/Package/Script/Python/gclient/gameplay/logic_base/spell': 'gclient/gameplay/logic_base/spell/',
        '/storage/emulated/0/Android/data/com.netease.newspikeme/files/Package/Script/Python/gclient/gameplay/logic_base/spell/spell_core': 'gclient/gameplay/logic_base/spell/spell_core/',
        '/storage/emulated/0/Android/data/com.netease.newspikeme/files/Package/Script/Python/engine/tools': 'engine/tools/',
        '/storage/emulated/0/Android/data/com.netease.newspikeme/files/Package/Script/Python/gclient/data_lang/data_en': 'gclient/data_lang/data_en/',
        '/storage/emulated/0/Android/data/com.netease.newspikeme/files/Package/Script/Python/gclient/framework/entities': 'gclient/framework/entities/',
        '/storage/emulated/0/Android/data/com.netease.newspikeme/files/Package/Script/Python/gshare/wanster': 'gshare/wanster/',
        '/storage/emulated/0/Android/data/com.netease.newspikeme/files/Package/Script/Python/gclient/framework/entities/avatarmembers': 'gclient/framework/entities/avatarmembers/',
        '/storage/emulated/0/Android/data/com.netease.newspikeme/files/Package/Script/Python/gclient/logic': 'gclient/logic/',
        '/storage/emulated/0/Android/data/com.netease.newspikeme/files/Package/Script/Python/gclient/gamesystem/uihall': 'gclient/gamesystem/uihall/',
        '/storage/emulated/0/Android/data/com.netease.newspikeme/files/Package/Script/Python/gclient/gamesystem/uihall/room': 'gclient/gamesystem/uihall/room/',
        '/storage/emulated/0/Android/data/com.netease.newspikeme/files/Package/Script/Python/gclient/framework/ui/commonnodes': 'gclient/framework/ui/commonnodes/',
        '/storage/emulated/0/Android/data/com.netease.newspikeme/files/Package/Script/Python/gshare/game_logic': 'gshare/game_logic/',
        '/storage/emulated/0/Android/data/com.netease.newspikeme/files/Package/Script/Python/gclient/ui/uilogin': 'gclient/ui/uilogin/',
        '/storage/emulated/0/Android/data/com.netease.newspikeme/files/Package/Script/Python/gclient/gamesystem/uigunsmith': 'gclient/gamesystem/uigunsmith/',
        '/storage/emulated/0/Android/data/com.netease.newspikeme/files/Package/Script/Python/gclient/gamesystem/uihall/gunupgrade': 'gclient/gamesystem/uihall/gunupgrade/',
        '/storage/emulated/0/Android/data/com.netease.newspikeme/files/Package/Script/Python/gclient/gamesystem/uihall/uimall': 'gclient/gamesystem/uihall/uimall/',
        '/storage/emulated/0/Android/data/com.netease.newspikeme/files/Package/Script/Python/gclient/framework/commoncomps': 'gclient/framework/commoncomps/',
        '/storage/emulated/0/Android/data/com.netease.newspikeme/files/Package/Script/Python/gclient/gameplay/logic_rookieguide': 'gclient/gameplay/logic_rookieguide/',
        '/storage/emulated/0/Android/data/com.netease.newspikeme/files/Package/Script/Python/gclient/gameplay/logic_rookieguide/ui': 'gclient/gameplay/logic_rookieguide/ui/',
        '/storage/emulated/0/Android/data/com.netease.newspikeme/files/Package/Script/Python/gclient/gameplay/uicomponents': 'gclient/gameplay/uicomponents/',
        '/storage/emulated/0/Android/data/com.netease.newspikeme/files/Package/Script/Python/gclient/util/iconbake': 'gclient/util/iconbake/',
        '/storage/emulated/0/Android/data/com.netease.newspikeme/files/Package/Script/Python/gclient/gameplay/logic_base/equips': 'gclient/gameplay/logic_base/equips/',
        '/storage/emulated/0/Android/data/com.netease.newspikeme/files/Package/Script/Python/gclient/gameplay/logic_base/models': 'gclient/gameplay/logic_base/models/',
        '/storage/emulated/0/Android/data/com.netease.newspikeme/files/Package/Script/Python/gclient/framework/models': 'gclient/framework/models/',
        '/storage/emulated/0/Android/data/com.netease.newspikeme/files/Package/Script/Python/gclient/util/cinematics': 'gclient/util/cinematics/',
        '/storage/emulated/0/Android/data/com.netease.newspikeme/files/Package/Script/Python/SunshineSDK': 'SunshineSDK/',
        '/storage/emulated/0/Android/data/com.netease.newspikeme/files/Package/Script/Python/SunshineSDK/Custom': 'SunshineSDK/Custom/',
        '/storage/emulated/0/Android/data/com.netease.newspikeme/files/Package/Script/Python/SunshineSDK/Meta': 'SunshineSDK/Meta/',
        '/storage/emulated/0/Android/data/com.netease.newspikeme/files/Package/Script/Python/gclient/gameplay/logic_base/ui': 'gclient/gameplay/logic_base/ui/',
        '/storage/emulated/0/Android/data/com.netease.newspikeme/files/Package/Script/Python/gclient/gameplay/logic_moba_zombie': 'gclient/gameplay/logic_moba_zombie/',
        '/storage/emulated/0/Android/data/com.netease.newspikeme/files/Package/Script/Python/gclient/gameplay/logic_moba_zombie/ui': 'gclient/gameplay/logic_moba_zombie/ui/',
        '/storage/emulated/0/Android/data/com.netease.newspikeme/files/Package/Script/Python/gclient/gamesystem/models': 'gclient/gamesystem/models/',
        '/storage/emulated/0/Android/data/com.netease.newspikeme/files/Package/Script/Python/gclient/gamesystem/uihall/game_map_choose': 'gclient/gamesystem/uihall/game_map_choose/',
        '/storage/emulated/0/Android/data/com.netease.newspikeme/files/Package/Script/Python/gclient/gamesystem/uihall/chat': 'gclient/gamesystem/uihall/chat/',
        '/storage/emulated/0/Android/data/com.netease.newspikeme/files/Package/Script/Python/gclient/gamesystem/uihall/clan': 'gclient/gamesystem/uihall/clan/',
        '/storage/emulated/0/Android/data/com.netease.newspikeme/files/Package/Script/Python/gclient/gamesystem/uihall/clan/util': 'gclient/gamesystem/uihall/clan/util/',
        '/storage/emulated/0/Android/data/com.netease.newspikeme/files/Package/Script/Python/gclient/gamesystem/uihall/clan/components': 'gclient/gamesystem/uihall/clan/components/',
        '/storage/emulated/0/Android/data/com.netease.newspikeme/files/Package/Script/Python/gclient/framework/camera': 'gclient/framework/camera/',
        '/storage/emulated/0/Android/data/com.netease.newspikeme/files/Package/Script/Python/SunshineSDK/Custom/Editor': 'SunshineSDK/Custom/Editor/',
        '/storage/emulated/0/Android/data/com.netease.newspikeme/files/Package/Script/Python/SunshineSDK/Custom/Editor/EditorMeta': 'SunshineSDK/Custom/Editor/EditorMeta/',
        '/storage/emulated/0/Android/data/com.netease.newspikeme/files/Package/Script/Python/SunshineSDK/Custom/Editor/EditorMeta/camera': 'SunshineSDK/Custom/Editor/EditorMeta/camera/',
        '/storage/emulated/0/Android/data/com.netease.newspikeme/files/Package/Script/Python/SunshineSDK/Custom/Editor/EditorMeta/weapon': 'SunshineSDK/Custom/Editor/EditorMeta/weapon/',
        '/storage/emulated/0/Android/data/com.netease.newspikeme/files/Package/Script/Python/SunshineSDK/Custom/Editor/EditorMeta/vehicle': 'SunshineSDK/Custom/Editor/EditorMeta/vehicle/',
        '/storage/emulated/0/Android/data/com.netease.newspikeme/files/Package/Script/Python/SunshineSDK/Custom/Entity': 'SunshineSDK/Custom/Entity/',
        '/storage/emulated/0/Android/data/com.netease.newspikeme/files/Package/Script/Python/SunshineSDK/Custom/Entity/Vehicle': 'SunshineSDK/Custom/Entity/Vehicle/',
        '/storage/emulated/0/Android/data/com.netease.newspikeme/files/Package/Script/Python/gclient/data/ets_data/camera': 'gclient/data/ets_data/camera/',
        '/storage/emulated/0/Android/data/com.netease.newspikeme/files/Package/Script/Python/gclient/gamesystem/entities/avatarmembers/activity_data_cls': 'gclient/gamesystem/entities/avatarmembers/activity_data_cls/',
        '/storage/emulated/0/Android/data/com.netease.newspikeme/files/Package/Script/Python/gshare/activity_data': 'gshare/activity_data/',
        '/storage/emulated/0/Android/data/com.netease.newspikeme/files/Package/Script/Python/gclient/gamesystem/uisettingnew': 'gclient/gamesystem/uisettingnew/',
        '/storage/emulated/0/Android/data/com.netease.newspikeme/files/Package/Script/Python/gclient/gameplay/logic_shootingrange': 'gclient/gameplay/logic_shootingrange/',
        '/storage/emulated/0/Android/data/com.netease.newspikeme/files/Package/Script/Python/gclient/gameplay/logic_shootingrange/ui': 'gclient/gameplay/logic_shootingrange/ui/',
        '/storage/emulated/0/Android/data/com.netease.newspikeme/files/Package/Script/Python/gclient/gamesystem/uihall/uipass': 'gclient/gamesystem/uihall/uipass/',
        '/storage/emulated/0/Android/data/com.netease.newspikeme/files/Package/Script/Python/gclient/gamesystem/uihero': 'gclient/gamesystem/uihero/',
        '/storage/emulated/0/Android/data/com.netease.newspikeme/files/Package/Script/Python/gclient/gamesystem/uiwarehouse': 'gclient/gamesystem/uiwarehouse/',
        '/storage/emulated/0/Android/data/com.netease.newspikeme/files/Package/Script/Python/gclient/gameplay/logic_moba': 'gclient/gameplay/logic_moba/',
        '/storage/emulated/0/Android/data/com.netease.newspikeme/files/Package/Script/Python/gclient/gameplay/logic_moba/ui': 'gclient/gameplay/logic_moba/ui/',
        '/storage/emulated/0/Android/data/com.netease.newspikeme/files/Package/Script/Python/gclient/gamesystem/uihall/uicalculation': 'gclient/gamesystem/uihall/uicalculation/',
        '/storage/emulated/0/Android/data/com.netease.newspikeme/files/Package/Script/Python/gclient/gamesystem/uihall/activity': 'gclient/gamesystem/uihall/activity/',
        '/storage/emulated/0/Android/data/com.netease.newspikeme/files/Package/Script/Python/gclient/gamesystem/uihall/activity/halloween': 'gclient/gamesystem/uihall/activity/halloween/',
        '/storage/emulated/0/Android/data/com.netease.newspikeme/files/Package/Script/Python/gclient/gamesystem/uihall/ui_personal_space': 'gclient/gamesystem/uihall/ui_personal_space/',
        '/storage/emulated/0/Android/data/com.netease.newspikeme/files/Package/Script/Python/gclient/gamesystem/uihall/activity/yearly_review': 'gclient/gamesystem/uihall/activity/yearly_review/',
        '/storage/emulated/0/Android/data/com.netease.newspikeme/files/Package/Script/Python/gclient/gameplay/logic_base/entities': 'gclient/gameplay/logic_base/entities/',
        '/storage/emulated/0/Android/data/com.netease.newspikeme/files/Package/Script/Python/gclient/gameplay/logic_base/comps': 'gclient/gameplay/logic_base/comps/',
        '/storage/emulated/0/Android/data/com.netease.newspikeme/files/Package/Script/Python/gclient/gameplay/logic_moba_first': 'gclient/gameplay/logic_moba_first/',
        '/storage/emulated/0/Android/data/com.netease.newspikeme/files/Package/Script/Python/gclient/gameplay/logic_moba_first/ui': 'gclient/gameplay/logic_moba_first/ui/',
        '/storage/emulated/0/Android/data/com.netease.newspikeme/files/Package/Script/Python/gclient/gameplay/logic_base/entities/combatavatarmembers': 'gclient/gameplay/logic_base/entities/combatavatarmembers/',
        '/storage/emulated/0/Android/data/com.netease.newspikeme/files/Package/Script/Python/gclient/gameplay/logic_base/bot': 'gclient/gameplay/logic_base/bot/',
        '/storage/emulated/0/Android/data/com.netease.newspikeme/files/Package/Script/Python/gshare/bot': 'gshare/bot/',
        '/storage/emulated/0/Android/data/com.netease.newspikeme/files/Package/Script/Python/HelenFramework/HelenAI': 'HelenFramework/HelenAI/',
        '/storage/emulated/0/Android/data/com.netease.newspikeme/files/Package/Script/Python/HelenFramework/HelenAI/ai_consts': 'HelenFramework/HelenAI/ai_consts/',
        '/storage/emulated/0/Android/data/com.netease.newspikeme/files/Package/Script/Python/gclient/gameplay/logic_base/entities/robotcomponents': 'gclient/gameplay/logic_base/entities/robotcomponents/'
    },
    'create_module': < bound method finder.create_module of < MImporter.finder object at 0x7b6ccfd510 >> ,
    'exec_module': < bound method finder.exec_module of < MImporter.finder object at 0x7b6ccfd510 >> ,
    'find_spec': < bound method finder.find_spec of < MImporter.finder object at 0x7b6ccfd510 >> ,
    'find_spec_in_anywhere': < bound method finder.find_spec_in_anywhere of < MImporter.finder object at 0x7b6ccfd510 >> ,
    'find_spec_in_encrypt': < bound method finder.find_spec_in_encrypt of < MImporter.finder object at 0x7b6ccfd510 >> ,
    'find_spec_in_patch_encrypt': < bound method finder.find_spec_in_patch_encrypt of < MImporter.finder object at 0x7b6ccfd510 >> ,
    'find_spec_in_pkg_encrypt': < bound method finder.find_spec_in_pkg_encrypt of < MImporter.finder object at 0x7b6ccfd510 >> ,
    'get_encrypt_name_with_path': < bound method finder.get_encrypt_name_with_path of < MImporter.finder object at 0x7b6ccfd510 >> ,
    'get_module': < bound method finder.get_module of < MImporter.finder object at 0x7b6ccfd510 >> ,
    'get_module_data': < bound method finder.get_module_data of < MImporter.finder object at 0x7b6ccfd510 >> ,
    'get_relpath': < bound method finder.get_relpath of < MImporter.finder object at 0x7b6ccfd510 >> ,
    'get_relpath_with_path': < bound method finder.get_relpath_with_path of < MImporter.finder object at 0x7b6ccfd510 >>
}