[10: 07: 06]: {
    'AddDebugDrawing': < bound method Space.AddDebugDrawing of < Space(Z5upctFT + syTbtig) >> ,
    'AddHighValueEffectItem': < bound method SpaceHighValueItemComp.AddHighValueEffectItem of < Space(Z5upctFT + syTbtig) >> ,
    'AddHudSceneCopyEnabledReason': < bound method HudSceneCopyController.AddHudSceneCopyEnabledReason of < Space(Z5upctFT + syTbtig) >> ,
    'AddPhysicsPostTick': < bound method Space.AddPhysicsPostTick of < Space(Z5upctFT + syTbtig) >> ,
    'AddSpacePostTick': < bound method Space.AddSpacePostTick of < Space(Z5upctFT + syTbtig) >> ,
    'AddWorldPreloadPivots': < bound method Space.AddWorldPreloadPivots of < Space(Z5upctFT + syTbtig) >> ,
    'AllOverlapByBox': < bound method Space.AllOverlapByBox of < Space(Z5upctFT + syTbtig) >> ,
    'AllOverlapByBox2': < bound method Space.AllOverlapByBox2 of < Space(Z5upctFT + syTbtig) >> ,
    'AllOverlapByBox3': < bound method Space.AllOverlapByBox3 of < Space(Z5upctFT + syTbtig) >> ,
    'AllOverlapByCapsule': < bound method Space.AllOverlapByCapsule of < Space(Z5upctFT + syTbtig) >> ,
    'AllOverlapByCircle': < bound method Space.AllOverlapByCircle of < Space(Z5upctFT + syTbtig) >> ,
    'AllOverlapByHorizontalCapsule': < bound method Space.AllOverlapByHorizontalCapsule of < Space(Z5upctFT + syTbtig) >> ,
    'AllRaycast': < bound method Space.AllRaycast of < Space(Z5upctFT + syTbtig) >> ,
    'AllRaycastBothway': < bound method Space.AllRaycastBothway of < Space(Z5upctFT + syTbtig) >> ,
    'AllSweepWithBox': < bound method Space.AllSweepWithBox of < Space(Z5upctFT + syTbtig) >> ,
    'AllSweepWithCapsule': < bound method Space.AllSweepWithCapsule of < Space(Z5upctFT + syTbtig) >> ,
    'AllSweepWithShape': < bound method Space.AllSweepWithShape of < Space(Z5upctFT + syTbtig) >> ,
    'AllSweepWithSphere': < bound method Space.AllSweepWithSphere of < Space(Z5upctFT + syTbtig) >> ,
    'ApplyMessage': < bound method SpaceStateLoaded.ApplyMessage of < Space(Z5upctFT + syTbtig) >> ,
    'BuildTransformFromCenter': < bound method Space.BuildTransformFromCenter of < Space(Z5upctFT + syTbtig) >> ,
    'CacheTireModels': < bound method SpaceVehicleCacheComp.CacheTireModels of < Space(Z5upctFT + syTbtig) >> ,
    'CacheVehicleConfig': < bound method SpaceVehicleCacheComp.CacheVehicleConfig of < Space(Z5upctFT + syTbtig) >> ,
    'CameraLeave': < bound method Space.CameraLeave of < Space(Z5upctFT + syTbtig) >> ,
    'CheckAndDoLoaded': < bound method SpaceStateLoaded.CheckAndDoLoaded of < Space(Z5upctFT + syTbtig) >> ,
    'CheckPythonThreadNum': < bound method Space.CheckPythonThreadNum of < Space(Z5upctFT + syTbtig) >> ,
    'CheckReuseForSpaceLoaded': < bound method Space.CheckReuseForSpaceLoaded of < Space(Z5upctFT + syTbtig) >> ,
    'ClearAllHighValueItem': < bound method SpaceHighValueItemComp.ClearAllHighValueItem of < Space(Z5upctFT + syTbtig) >> ,
    'ClearEntityMessage': < bound method Space.ClearEntityMessage of < Space(Z5upctFT + syTbtig) >> ,
    'ClearVehicleConfigCache': < bound method SpaceVehicleCacheComp.ClearVehicleConfigCache of < Space(Z5upctFT + syTbtig) >> ,
    'ClosestRaycast': < bound method Space.ClosestRaycast of < Space(Z5upctFT + syTbtig) >> ,
    'ClosestRaycastBone': < bound method Space.ClosestRaycastBone of < Space(Z5upctFT + syTbtig) >> ,
    'ClosestSweepWithBox': < bound method Space.ClosestSweepWithBox of < Space(Z5upctFT + syTbtig) >> ,
    'CombatAvatarsInRange': < bound method Space.CombatAvatarsInRange of < Space(Z5upctFT + syTbtig) >> ,
    'DelayClearDebugDrawings': < gshare.async_util.AsyncDescriptor object at 0x781b7ef550 > ,
    'DoQueryLandPosition': < bound method Space.DoQueryLandPosition of < Space(Z5upctFT + syTbtig) >> ,
    'DoStartLoading': < bound method SpaceStateLoading.DoStartLoading of < Space(Z5upctFT + syTbtig) >> ,
    'DrawBoxOverlapDebugInfo': < bound method Space.DrawBoxOverlapDebugInfo of < Space(Z5upctFT + syTbtig) >> ,
    'DrawCapsuleOverlapDebugInfo': < bound method Space.DrawCapsuleOverlapDebugInfo of < Space(Z5upctFT + syTbtig) >> ,
    'DrawCircleOverlapDebugInfo': < bound method Space.DrawCircleOverlapDebugInfo of < Space(Z5upctFT + syTbtig) >> ,
    'DrawHitResults': < bound method Space.DrawHitResults of < Space(Z5upctFT + syTbtig) >> ,
    'DrawRawCastDebugInfo': < bound method Space.DrawRawCastDebugInfo of < Space(Z5upctFT + syTbtig) >> ,
    'DrawRay': < bound method Space.DrawRay of < Space(Z5upctFT + syTbtig) >> ,
    'EnterUIStage': < bound method Space.EnterUIStage of < Space(Z5upctFT + syTbtig) >> ,
    'EntitiesInRange': < bound method Space.EntitiesInRange of < Space(Z5upctFT + syTbtig) >> ,
    'ExitUIStage': < bound method Space.ExitUIStage of < Space(Z5upctFT + syTbtig) >> ,
    'FSMBootstrap': < bound method FiniteStateMachine.FSMBootstrap of < Space(Z5upctFT + syTbtig) >> ,
    'FSMForceTransfer': < bound method FiniteStateMachine.FSMForceTransfer of < Space(Z5upctFT + syTbtig) >> ,
    'FSMGetHandler': < bound method FiniteStateMachine.FSMGetHandler of < Space(Z5upctFT + syTbtig) >> ,
    'FSMShutdown': < bound method FiniteStateMachine.FSMShutdown of < Space(Z5upctFT + syTbtig) >> ,
    'FSMTick': < bound method FiniteStateMachine.FSMTick of < Space(Z5upctFT + syTbtig) >> ,
    'FSMTransfer': < bound method FiniteStateMachine.FSMTransfer of < Space(Z5upctFT + syTbtig) >> ,
    'FindAndInitTerrain': < bound method SpaceStateLoaded.FindAndInitTerrain of < Space(Z5upctFT + syTbtig) >> ,
    'GeometryFactor': 1.0,
    'GetEntitiesByType': < bound method Space.GetEntitiesByType of < Space(Z5upctFT + syTbtig) >> ,
    'GetEntity': < bound method Space.GetEntity of < Space(Z5upctFT + syTbtig) >> ,
    'GetEntityByID': < bound method Space.GetEntityByID of < Space(Z5upctFT + syTbtig) >> ,
    'GetEntityInLevelByName': < bound method Space.GetEntityInLevelByName of < Space(Z5upctFT + syTbtig) >> ,
    'GetEntityInLevelByPrefix': < bound method Space.GetEntityInLevelByPrefix of < Space(Z5upctFT + syTbtig) >> ,
    'GetLandTransform': < bound method Space.GetLandTransform of < Space(Z5upctFT + syTbtig) >> ,
    'GetPhysicsShapeWrapper': < bound method Space.GetPhysicsShapeWrapper of < Space(Z5upctFT + syTbtig) >> ,
    'GetSceneEntity': < bound method Space.GetSceneEntity of < Space(Z5upctFT + syTbtig) >> ,
    'GetSceneEntityInWorld': < bound method Space.GetSceneEntityInWorld of < Space(Z5upctFT + syTbtig) >> ,
    'GetVehicleCompByProtoId': < bound method SpaceVehicleCacheComp.GetVehicleCompByProtoId of < Space(Z5upctFT + syTbtig) >> ,
    'GetVehicleConfigByProtoId': < bound method SpaceVehicleCacheComp.GetVehicleConfigByProtoId of < Space(Z5upctFT + syTbtig) >> ,
    'GetVehicleTireModel': < bound method SpaceVehicleCacheComp.GetVehicleTireModel of < Space(Z5upctFT + syTbtig) >> ,
    'GetWorldStoryboardSpeed': < bound method Space.GetWorldStoryboardSpeed of < Space(Z5upctFT + syTbtig) >> ,
    'InitData': < bound method Space.InitData of < Space(Z5upctFT + syTbtig) >> ,
    'IsConnectPoint': < bound method Space.IsConnectPoint of < Space(Z5upctFT + syTbtig) >> ,
    'IsHighWorld': < bound method Space.IsHighWorld of < Space(Z5upctFT + syTbtig) >> ,
    'LevelEnterOrLeaveWorld': < bound method Space.LevelEnterOrLeaveWorld of < Space(Z5upctFT + syTbtig) >> ,
    'LoadSpaceWorldData': < bound method Space.LoadSpaceWorldData of < Space(Z5upctFT + syTbtig) >> ,
    'LoadedCheckPivotalEntities': < bound method SpaceStateLoaded.LoadedCheckPivotalEntities of < Space(Z5upctFT + syTbtig) >> ,
    'LoadedNotifyFinishingLoading': < bound method SpaceStateLoaded.LoadedNotifyFinishingLoading of < Space(Z5upctFT + syTbtig) >> ,
    'LoadedShowCachedEntities': < bound method SpaceStateLoaded.LoadedShowCachedEntities of < Space(Z5upctFT + syTbtig) >> ,
    'MOBA_SPACENOS': {
        25,
        10
    },
    'NAME': 'StateCached',
    'NotifyGameSoundToAI': < bound method Space.NotifyGameSoundToAI of < Space(Z5upctFT + syTbtig) >> ,
    'OnAvatarModelLoaded': < bound method Space.OnAvatarModelLoaded of < Space(Z5upctFT + syTbtig) >> ,
    'OnBatchNotifySound': < bound method Space.OnBatchNotifySound of < Space(Z5upctFT + syTbtig) >> ,
    'OnEntityEnterOrLeaveWorldForTrigger': < bound method SpaceWeatherComp.OnEntityEnterOrLeaveWorldForTrigger of < Space(Z5upctFT + syTbtig) >> ,
    'OnPhysicsPostTick': < bound method Space.OnPhysicsPostTick of < Space(Z5upctFT + syTbtig) >> ,
    'OnPlayerBecomeZombieSpace': < bound method SpaceHighValueItemComp.OnPlayerBecomeZombieSpace of < Space(Z5upctFT + syTbtig) >> ,
    'OnPlayerCombatAvatarCreateSpace': < bound method SpaceHighValueItemComp.OnPlayerCombatAvatarCreateSpace of < Space(Z5upctFT + syTbtig) >> ,
    'OnReaplayPlayerBecomeZombieSpace': < bound method SpaceHighValueItemComp.OnReaplayPlayerBecomeZombieSpace of < Space(Z5upctFT + syTbtig) >> ,
    'OnReplayPlayerCreatedSpace': < bound method SpaceHighValueItemComp.OnReplayPlayerCreatedSpace of < Space(Z5upctFT + syTbtig) >> ,
    'OnSceneEntityEnterWorld': < bound method SpaceStateLoading.OnSceneEntityEnterWorld of < Space(Z5upctFT + syTbtig) >> ,
    'OnSceneEntityEnterWorldNotification': < bound method Space.OnSceneEntityEnterWorldNotification of < Space(Z5upctFT + syTbtig) >> ,
    'OnSceneEntityLeaveWorld': < bound method SpaceStateLoading.OnSceneEntityLeaveWorld of < Space(Z5upctFT + syTbtig) >> ,
    'OnSceneEntityLeaveWorldNotification': < bound method Space.OnSceneEntityLeaveWorldNotification of < Space(Z5upctFT + syTbtig) >> ,
    'OnScriptLodModelEnterOrLeaveWorld': < bound method SpaceStateLoading.OnScriptLodModelEnterOrLeaveWorld of < Space(Z5upctFT + syTbtig) >> ,
    'OnSpacePostTick': < bound method Space.OnSpacePostTick of < Space(Z5upctFT + syTbtig) >> ,
    'OnStateCachedEnter': < bound method SpaceStateCached.OnEnter of < Space(Z5upctFT + syTbtig) >> ,
    'OnStateEmptyEnter': < bound method SpaceStateEmpty.OnEnter of < Space(Z5upctFT + syTbtig) >> ,
    'OnStateLoadedEnter': < bound method SpaceStateLoaded.OnEnter of < Space(Z5upctFT + syTbtig) >> ,
    'OnStateLoadedExit': < bound method SpaceStateLoaded.OnExit of < Space(Z5upctFT + syTbtig) >> ,
    'OnStateLoadingEnter': < bound method SpaceStateLoading.OnEnter of < Space(Z5upctFT + syTbtig) >> ,
    'OnStateLoadingExit': < bound method SpaceStateLoading.OnExit of < Space(Z5upctFT + syTbtig) >> ,
    'OnTriggerForBoxInHouse': < bound method SpaceWeatherComp.OnTriggerForBoxInHouse of < Space(Z5upctFT + syTbtig) >> ,
    'OwnerLeave': < bound method Space.OwnerLeave of < Space(Z5upctFT + syTbtig) >> ,
    'PopPrincipleRole': < bound method SpacePrincipleRoleModifier.PopPrincipleRole of < Space(Z5upctFT + syTbtig) >> ,
    'PushPrincipleRole': < bound method SpacePrincipleRoleModifier.PushPrincipleRole of < Space(Z5upctFT + syTbtig) >> ,
    'QueryLandName': < bound method Space.QueryLandName of < Space(Z5upctFT + syTbtig) >> ,
    'QueryLandPosition': < bound method Space.QueryLandPosition of < Space(Z5upctFT + syTbtig) >> ,
    'QueryScreenPointLandTransform': < bound method Space.QueryScreenPointLandTransform of < Space(Z5upctFT + syTbtig) >> ,
    'RawRaycast': < bound method Space.RawRaycast of < Space(Z5upctFT + syTbtig) >> ,
    'RaycastBoneWithPenetrate': < bound method Space.RaycastBoneWithPenetrate of < Space(Z5upctFT + syTbtig) >> ,
    'RaycastBoneWithPenetrateBothway': < bound method Space.RaycastBoneWithPenetrateBothway of < Space(Z5upctFT + syTbtig) >> ,
    'RaycastWithPenetrate': < bound method Space.RaycastWithPenetrate of < Space(Z5upctFT + syTbtig) >> ,
    'RecordCombatItemLiveTime': < bound method Space.RecordCombatItemLiveTime of < Space(Z5upctFT + syTbtig) >> ,
    'RefreshHighValueEffectItems': < bound method SpaceHighValueItemComp.RefreshHighValueEffectItems of < Space(Z5upctFT + syTbtig) >> ,
    'RefreshPrincipleRole': < bound method SpacePrincipleRoleModifier.RefreshPrincipleRole of < Space(Z5upctFT + syTbtig) >> ,
    'ReloadWaterTrigger': < bound method SpaceWaterTriggerComp.ReloadWaterTrigger of < Space(Z5upctFT + syTbtig) >> ,
    'RemoveDummyEntity': < bound method Space.RemoveDummyEntity of < Space(Z5upctFT + syTbtig) >> ,
    'RemoveHighValueEffectItem': < bound method SpaceHighValueItemComp.RemoveHighValueEffectItem of < Space(Z5upctFT + syTbtig) >> ,
    'RemoveHudSceneCopyEnabledReason': < bound method HudSceneCopyController.RemoveHudSceneCopyEnabledReason of < Space(Z5upctFT + syTbtig) >> ,
    'RemovePhysicsPostTick': < bound method Space.RemovePhysicsPostTick of < Space(Z5upctFT + syTbtig) >> ,
    'RemoveSpacePostTick': < bound method Space.RemoveSpacePostTick of < Space(Z5upctFT + syTbtig) >> ,
    'RemoveWorldPreloadPivots': < bound method Space.RemoveWorldPreloadPivots of < Space(Z5upctFT + syTbtig) >> ,
    'RestoreWeatherStateOnLoaded': < bound method SpaceWeatherComp.RestoreWeatherStateOnLoaded of < Space(Z5upctFT + syTbtig) >> ,
    'SetGlobalPhysic': < bound method Space.SetGlobalPhysic of < Space(Z5upctFT + syTbtig) >> ,
    'SetHudSceneCopyEnabledWithReason': < bound method HudSceneCopyController.SetHudSceneCopyEnabledWithReason of < Space(Z5upctFT + syTbtig) >> ,
    'SetObservationPoints': < bound method Space.SetObservationPoints of < Space(Z5upctFT + syTbtig) >> ,
    'SetPreloadPivotsAndDistance': < bound method Space.SetPreloadPivotsAndDistance of < Space(Z5upctFT + syTbtig) >> ,
    'SetRootPrincipleRole': < bound method SpacePrincipleRoleModifier.SetRootPrincipleRole of < Space(Z5upctFT + syTbtig) >> ,
    'SetWeather': < bound method SpaceWeatherComp.SetWeather of < Space(Z5upctFT + syTbtig) >> ,
    'SetWorldStoryboardSpeed': < bound method Space.SetWorldStoryboardSpeed of < Space(Z5upctFT + syTbtig) >> ,
    'ShowEntitiesCount': < bound method Space.ShowEntitiesCount of < Space(Z5upctFT + syTbtig) >> ,
    'SphereSweepCollisionBone': < bound method Space.SphereSweepCollisionBone of < Space(Z5upctFT + syTbtig) >> ,
    'StatClientEntity': < bound method Space.StatClientEntity of < Space(Z5upctFT + syTbtig) >> ,
    'StatEntity': < bound method Space.StatEntity of < Space(Z5upctFT + syTbtig) >> ,
    'StatMaxClientEntity': < bound method Space.StatMaxClientEntity of < Space(Z5upctFT + syTbtig) >> ,
    'StatMaxClientEntityImply': < bound method Space.StatMaxClientEntityImply of < Space(Z5upctFT + syTbtig) >> ,
    'StatMaxDistanceEntity': < bound method Space.StatMaxDistanceEntity of < Space(Z5upctFT + syTbtig) >> ,
    'TerrainLodThreshold': < 0.0000,
    0.0000,
    0.0000 > ,
    'TerrainMaxLoadingDistance': -1,
    'TickPreloadPivotsAndDistance': < bound method Space.TickPreloadPivotsAndDistance of < Space(Z5upctFT + syTbtig) >> ,
    'TickScriptLodModel': < bound method SpaceStateLoading.TickScriptLodModel of < Space(Z5upctFT + syTbtig) >> ,
    'TimerLogSomething': < bound method Space.TimerLogSomething of < Space(Z5upctFT + syTbtig) >> ,
    'TryCacheDestroyedVehicleTires': < bound method SpaceVehicleCacheComp.TryCacheDestroyedVehicleTires of < Space(Z5upctFT + syTbtig) >> ,
    'TryCacheVehicleCompOnDestroyed': < bound method SpaceVehicleCacheComp.TryCacheVehicleCompOnDestroyed of < Space(Z5upctFT + syTbtig) >> ,
    'UnloadSpaceWorldData': < bound method Space.UnloadSpaceWorldData of < Space(Z5upctFT + syTbtig) >> ,
    'UpdateWorldPreloadPivots': < bound method Space.UpdateWorldPreloadPivots of < Space(Z5upctFT + syTbtig) >> ,
    '_CacheVehicleComps': < bound method SpaceVehicleCacheComp._CacheVehicleComps of < Space(Z5upctFT + syTbtig) >> ,
    '_CanDoVehicleCache': < bound method SpaceVehicleCacheComp._CanDoVehicleCache of < Space(Z5upctFT + syTbtig) >> ,
    '_CheckReuseForSpaceLoadedFunc': < bound method Space._CheckReuseForSpaceLoadedFunc of < Space(Z5upctFT + syTbtig) >> ,
    '_CreateTireModelByUnitId': < bound method SpaceVehicleCacheComp._CreateTireModelByUnitId of < Space(Z5upctFT + syTbtig) >> ,
    '_CreateVehicleVehicleByParam': < bound method SpaceVehicleCacheComp._CreateVehicleVehicleByParam of < Space(Z5upctFT + syTbtig) >> ,
    '_InitCalcStutterCount': < bound method Space._InitCalcStutterCount of < Space(Z5upctFT + syTbtig) >> ,
    '_SetHudSceneCopyEnabled': < bound method HudSceneCopyController._SetHudSceneCopyEnabled of < Space(Z5upctFT + syTbtig) >> ,
    '__class__': < class 'gclient.framework.entities.space.Space' > ,
    '__clear_cached_properties__': < bound method Entity.__clear_cached_properties__ of < Space(Z5upctFT + syTbtig) >> ,
    '__components__': [ < class 'gshare.fsm.FiniteStateMachine' > , < class 'gclient.framework.entities.space.SpaceStateEmpty' > , < class 'gclient.framework.entities.space.SpaceStateLoading' > , < class 'gclient.framework.entities.space.SpaceStateLoaded' > , < class 'gclient.framework.entities.space.SpaceStateCached' > , < class 'gclient.framework.commoncomps.space_weather_comp.SpaceWeatherComp' > , < class 'gclient.framework.commoncomps.space_vehicle_cache_comp.SpaceVehicleCacheComp' > , < class 'gclient.framework.commoncomps.space_water_trigger.SpaceWaterTriggerComp' > , < class 'gclient.framework.entities.space.HudSceneCopyController' > , < class 'gclient.framework.commoncomps.space_high_value_item_comp.SpaceHighValueItemComp' > , < class 'gclient.framework.entities.space.SpacePrincipleRoleModifier' > ],
    '__delattr__': < method - wrapper '__delattr__' of Space object at 0x73fff1c800 > ,
    '__dict__': {
        '_is_deactive': False,
        '_is_destroyed': False,
        'id': 'Z5upctFT+syTbtig',
        '_timers': {
            -28: < built - in method clear of dict object at 0x73fff1c480 > ,
            -31: < bound method SpaceStateLoading.TickScriptLodModel of < Space(Z5upctFT + syTbtig) >> ,
            -51: < bound method Space.TickPreloadPivotsAndDistance of < Space(Z5upctFT + syTbtig) >> ,
            -52: < bound method Space.OnBatchNotifySound of < Space(Z5upctFT + syTbtig) >> ,
            -77: < function Space.TimerLogSomething. < locals > ._report_performace at 0x781b543740 > ,
            -78: < function Space.TimerLogSomething. < locals > ._report_sec at 0x781b5437e0 > ,
            -79: < function Space.TimerLogSomething. < locals > ._report_live_time at 0x781b543880 >
        },
        '_tick_timer': 0,
        'spaceno': 14,
        'owner': < PlayerAvatar(A + pUrwUSaBFTuCIK) > ,
        'entities': {
            'Z5uqYdFT+syTbxiB': < CombatTeamEntity_ShootingRange(Z5uqYdFT + syTbxiB) > ,
            'Z5uqYdFT+syTbxh8': < PlayerCombatAvatarShootingRange(Z5uqYdFT + syTbxh8) > ,
            'Z5upctFT+syTbtih': < GameLogicShootingRange(Z5upctFT + syTbtih) > ,
            'Z5upctFT+syTbtip': < RobotCombatAvatarShootingRange(Z5upctFT + syTbtip) > ,
            'Z5upctFT+syTbtil': < RobotCombatAvatarShootingRange(Z5upctFT + syTbtil) > ,
            'Z5upctFT+syTbtiz': < RobotCombatAvatarShootingRange(Z5upctFT + syTbtiz) > ,
            'Z5upctFT+syTbtiu': < RobotCombatAvatarShootingRange(Z5upctFT + syTbtiu) > ,
            'Z5upctFT+syTbti5': < RobotCombatAvatarShootingRange(Z5upctFT + syTbti5) > ,
            'Z5upctFT+syTbti9': < RobotCombatAvatarShootingRange(Z5upctFT + syTbti9) > ,
            'Z5uqYdFT+syTbxiD': < Bomb(Z5uqYdFT + syTbxiD) >
        },
        'world': < IWorld object at 0x781b611400 > ,
        'loader': < gclient.framework.entities.space.SpaceLoader object at 0x784307da50 > ,
        'camera': < gclient.framework.entities.camera.Camera object at 0x7817ef54d0 > ,
        'terrain_inner': None,
        'game_logic': < GameLogicShootingRange(Z5upctFT + syTbtih) > ,
        'is_relay': False,
        'uistage_type': 4,
        'current_stage': < class 'gclient.gameplay.logic_shootingrange.ui.main_uistage.ShootingRangeMainStage' > ,
        'is_in_hall': False,
        'is_seamless_load': False,
        'dist_aoi_guids': {},
        'replay_game_logic_id': '',
        'replay_kind': 1,
        'entity_category': defaultdict( < class 'dict' > , {
            'CombatAvatar': {
                'Z5uqYdFT+syTbxh8': < PlayerCombatAvatarShootingRange(Z5uqYdFT + syTbxh8) > ,
                'Z5upctFT+syTbtip': < RobotCombatAvatarShootingRange(Z5upctFT + syTbtip) > ,
                'Z5upctFT+syTbtil': < RobotCombatAvatarShootingRange(Z5upctFT + syTbtil) > ,
                'Z5upctFT+syTbtiz': < RobotCombatAvatarShootingRange(Z5upctFT + syTbtiz) > ,
                'Z5upctFT+syTbtiu': < RobotCombatAvatarShootingRange(Z5upctFT + syTbtiu) > ,
                'Z5upctFT+syTbti5': < RobotCombatAvatarShootingRange(Z5upctFT + syTbti5) > ,
                'Z5upctFT+syTbti9': < RobotCombatAvatarShootingRange(Z5upctFT + syTbti9) >
            },
            'CombatTeamEntity_ShootingRange': {
                'Z5uqYdFT+syTbxiB': < CombatTeamEntity_ShootingRange(Z5uqYdFT + syTbxiB) >
            },
            'PlayerCombatAvatarShootingRange': {
                'Z5uqYdFT+syTbxh8': < PlayerCombatAvatarShootingRange(Z5uqYdFT + syTbxh8) >
            },
            'GameLogicShootingRange': {
                'Z5upctFT+syTbtih': < GameLogicShootingRange(Z5upctFT + syTbtih) >
            },
            'RobotCombatAvatarShootingRange': {
                'Z5upctFT+syTbtip': < RobotCombatAvatarShootingRange(Z5upctFT + syTbtip) > ,
                'Z5upctFT+syTbtil': < RobotCombatAvatarShootingRange(Z5upctFT + syTbtil) > ,
                'Z5upctFT+syTbtiz': < RobotCombatAvatarShootingRange(Z5upctFT + syTbtiz) > ,
                'Z5upctFT+syTbtiu': < RobotCombatAvatarShootingRange(Z5upctFT + syTbtiu) > ,
                'Z5upctFT+syTbti5': < RobotCombatAvatarShootingRange(Z5upctFT + syTbti5) > ,
                'Z5upctFT+syTbti9': < RobotCombatAvatarShootingRange(Z5upctFT + syTbti9) >
            },
            'Bomb': {
                'Z5uqYdFT+syTbxiD': < Bomb(Z5uqYdFT + syTbxiD) >
            }
        }),
        'combat_avatars': {
            'Z5uqYdFT+syTbxh8': < PlayerCombatAvatarShootingRange(Z5uqYdFT + syTbxh8) > ,
            'Z5upctFT+syTbtip': < RobotCombatAvatarShootingRange(Z5upctFT + syTbtip) > ,
            'Z5upctFT+syTbtil': < RobotCombatAvatarShootingRange(Z5upctFT + syTbtil) > ,
            'Z5upctFT+syTbtiz': < RobotCombatAvatarShootingRange(Z5upctFT + syTbtiz) > ,
            'Z5upctFT+syTbtiu': < RobotCombatAvatarShootingRange(Z5upctFT + syTbtiu) > ,
            'Z5upctFT+syTbti5': < RobotCombatAvatarShootingRange(Z5upctFT + syTbti5) > ,
            'Z5upctFT+syTbti9': < RobotCombatAvatarShootingRange(Z5upctFT + syTbti9) >
        },
        'dummy_entities': {},
        'area_hooks': [],
        'physics_tickers': set(),
        'physics_tick_inloop': False,
        'physics_tick_pending': [],
        'space_tickers': set(),
        'space_tick_inloop': False,
        'space_tick_pending': [],
        'registry': {},
        'batch_notify_sound_ticker': -52,
        'batch_notify_sound_queue': defaultdict( < class 'dict' > , {}),
        'query_land_cache': {},
        'query_land_cache_total': 0,
        'query_land_cache_hits': 0,
        'query_land_cache_ticker': -28,
        'preload_pivot_clear_timer': -51,
        'world_preload_pivots': defaultdict( < class 'list' > , {}),
        'world_preload_pivots_deadline': defaultdict( < class 'float' > , {}),
        'observation_point_deadline': 0.0,
        'timer_log_elk': -77,
        'timer_log_qsec': -78,
        'timer_live_timer': -79,
        'timer_check_python': None,
        'loading_time': 0.4265444278717041,
        'weather_mgr': < gclient.util.weather_util.WeatherManager object at 0x73fff1c150 > ,
        'cache_vehicle_configs': {},
        'cache_vehicle_comps': {},
        'cache_vehicle_tire_models': {},
        'hud_scene_copy_enabled_reason': 0,
        'high_value_effect_items': set(),
        'space_principle_role_mgr': < SpacePrincipleRoleMgr(0x0 x73fff14290) > ,
        '_debug_drawings': {},
        '_debug_drawing_count': 0,
        'global_store_info': {},
        'world_ientity_dict': {},
        'world_ientity_building_dict': {},
        'building_data': None,
        'proto': {
            'entrance_list': ((-16.621, 0.042, -6.784, 89.9), ),
            'name': 'Range',
            'id': 14,
            'map': 'shootingrange_test2'
        },
        'is_si_island': False,
        'is_high_world': None,
        'state': 'StateLoaded',
        'prev_state': 'StateLoading',
        'fsm_target_state': 'StateLoaded',
        'frame_delta': 0,
        'fsm_tick_func': None,
        'combat_item_octree': < gclient.gameplay.logic_base.entities.combat_item.CombatItemOctreeManager object at 0x73fff142d0 > ,
        'combat_item_live_time': {},
        'physics_shape_wrap': < PhysicsShapeWrapper object at 0x73fe32d280 > ,
        'script_lod_model_ticker': -31,
        'script_lod_models': {},
        'script_lod_model_distance': 100,
        'script_lod_model_building_distance': 100,
        'loading_start_checker': None,
        'start_loading_time': 1738255020.3784173,
        'loaded_ticket': 'Z5uqrEIaqTAC3h7O',
        'loaded_timer': None,
        'last_stutter_count': 23
    },
    '__dir__': < built - in method __dir__ of Space object at 0x73fff1c800 > ,
    '__doc__': None,
    '__eq__': < method - wrapper '__eq__' of Space object at 0x73fff1c800 > ,
    '__format__': < built - in method __format__ of Space object at 0x73fff1c800 > ,
    '__ge__': < method - wrapper '__ge__' of Space object at 0x73fff1c800 > ,
    '__getattribute__': < method - wrapper '__getattribute__' of Space object at 0x73fff1c800 > ,
    '__getstate__': < built - in method __getstate__ of Space object at 0x73fff1c800 > ,
    '__gt__': < method - wrapper '__gt__' of Space object at 0x73fff1c800 > ,
    '__hash__': < method - wrapper '__hash__' of Space object at 0x73fff1c800 > ,
    '__init__': < bound method ClientSpace.__init__ of < Space(Z5upctFT + syTbtig) >> ,
    '__init_subclass__': < built - in method __init_subclass__ of EntityMetaClass object at 0x7824007c10 > ,
    '__le__': < method - wrapper '__le__' of Space object at 0x73fff1c800 > ,
    '__lt__': < method - wrapper '__lt__' of Space object at 0x73fff1c800 > ,
    '__module__': 'gclient.framework.entities.space',
    '__ne__': < method - wrapper '__ne__' of Space object at 0x73fff1c800 > ,
    '__new__': < function ClientSpace.__new__ at 0x78e50100e0 > ,
    '__property_all__': {},
    '__property_flag__': {},
    '__reduce__': < built - in method __reduce__ of Space object at 0x73fff1c800 > ,
    '__reduce_ex__': < built - in method __reduce_ex__ of Space object at 0x73fff1c800 > ,
    '__repr__': < bound method Entity.__repr__ of < Space(Z5upctFT + syTbtig) >> ,
    '__setattr__': < method - wrapper '__setattr__' of Space object at 0x73fff1c800 > ,
    '__sizeof__': < built - in method __sizeof__ of Space object at 0x73fff1c800 > ,
    '__str__': < bound method Entity.__str__ of < Space(Z5upctFT + syTbtig) >> ,
    '__subclasshook__': < built - in method __subclasshook__ of EntityMetaClass object at 0x7824007c10 > ,
    '__weakref__': None,
    '_addComponent': < bound method _addComponent of < class 'gclient.framework.entities.space.Space' >> ,
    '_callComponents': < bound method _callComponents of < Space(Z5upctFT + syTbtig) >> ,
    '_debug_drawing_count': 0,
    '_debug_drawings': {},
    '_debug_high_value_items': < bound method SpaceHighValueItemComp._debug_high_value_items of < Space(Z5upctFT + syTbtig) >> ,
    '_delComponent': < bound method _delComponent of < class 'gclient.framework.entities.space.Space' >> ,
    '_finiComponents': < bound method _finiComponents of < Space(Z5upctFT + syTbtig) >> ,
    '_initComponents': < bound method _initComponents of < Space(Z5upctFT + syTbtig) >> ,
    '_instance': < Space(Z5upctFT + syTbtig) > ,
    '_is_deactive': False,
    '_is_destroyed': False,
    '_onCalcStutterCount': < bound method Space._onCalcStutterCount of < Space(Z5upctFT + syTbtig) >> ,
    '_on_timer': < bound method Entity._on_timer of < Space(Z5upctFT + syTbtig) >> ,
    '_postComponents': < bound method _postComponents of < Space(Z5upctFT + syTbtig) >> ,
    '_tickComponents': < bound method _tickComponents of < Space(Z5upctFT + syTbtig) >> ,
    '_tick_timer': 0,
    '_timers': {
        -28: < built - in method clear of dict object at 0x73fff1c480 > ,
        -31: < bound method SpaceStateLoading.TickScriptLodModel of < Space(Z5upctFT + syTbtig) >> ,
        -51: < bound method Space.TickPreloadPivotsAndDistance of < Space(Z5upctFT + syTbtig) >> ,
        -52: < bound method Space.OnBatchNotifySound of < Space(Z5upctFT + syTbtig) >> ,
        -77: < function Space.TimerLogSomething. < locals > ._report_performace at 0x781b543740 > ,
        -78: < function Space.TimerLogSomething. < locals > ._report_sec at 0x781b5437e0 > ,
        -79: < function Space.TimerLogSomething. < locals > ._report_live_time at 0x781b543880 >
    },
    'add_repeat_timer': < bound method Entity.add_repeat_timer of < Space(Z5upctFT + syTbtig) >> ,
    'add_timer': < bound method Entity.add_timer of < Space(Z5upctFT + syTbtig) >> ,
    'area': 'igetattr.error',
    'area_hooks': [],
    'batch_notify_sound_queue': defaultdict( < class 'dict' > , {}),
    'batch_notify_sound_ticker': -52,
    'building_data': None,
    'cache': < bound method Space.cache of < Space(Z5upctFT + syTbtig) >> ,
    'cache_vehicle_comps': {},
    'cache_vehicle_configs': {},
    'cache_vehicle_tire_models': {},
    'camera': < gclient.framework.entities.camera.Camera object at 0x7817ef54d0 > ,
    'can_modify_billboard_distance': False,
    'cancel_timer': < bound method Entity.cancel_timer of < Space(Z5upctFT + syTbtig) >> ,
    'combat_avatars': {
        'Z5uqYdFT+syTbxh8': < PlayerCombatAvatarShootingRange(Z5uqYdFT + syTbxh8) > ,
        'Z5upctFT+syTbtip': < RobotCombatAvatarShootingRange(Z5upctFT + syTbtip) > ,
        'Z5upctFT+syTbtil': < RobotCombatAvatarShootingRange(Z5upctFT + syTbtil) > ,
        'Z5upctFT+syTbtiz': < RobotCombatAvatarShootingRange(Z5upctFT + syTbtiz) > ,
        'Z5upctFT+syTbtiu': < RobotCombatAvatarShootingRange(Z5upctFT + syTbtiu) > ,
        'Z5upctFT+syTbti5': < RobotCombatAvatarShootingRange(Z5upctFT + syTbti5) > ,
        'Z5upctFT+syTbti9': < RobotCombatAvatarShootingRange(Z5upctFT + syTbti9) >
    },
    'combat_item_live_time': {},
    'combat_item_octree': < gclient.gameplay.logic_base.entities.combat_item.CombatItemOctreeManager object at 0x73fff142d0 > ,
    'create_entity': < bound method Space.create_entity of < Space(Z5upctFT + syTbtig) >> ,
    'current_stage': < class 'gclient.gameplay.logic_shootingrange.ui.main_uistage.ShootingRangeMainStage' > ,
    'deactive': < bound method Entity.deactive of < Space(Z5upctFT + syTbtig) >> ,
    'destroy': < bound method EntityMetaClass.replaceDestroy. < locals > .destroy of < Space(Z5upctFT + syTbtig) >> ,
    'destroyObject': < bound method Entity.destroyObject of < Space(Z5upctFT + syTbtig) >> ,
    'dist_aoi_guids': {},
    'dummy_entities': {},
    'enter': < bound method Space.enter of < Space(Z5upctFT + syTbtig) >> ,
    'entities': {
        'Z5uqYdFT+syTbxiB': < CombatTeamEntity_ShootingRange(Z5uqYdFT + syTbxiB) > ,
        'Z5uqYdFT+syTbxh8': < PlayerCombatAvatarShootingRange(Z5uqYdFT + syTbxh8) > ,
        'Z5upctFT+syTbtih': < GameLogicShootingRange(Z5upctFT + syTbtih) > ,
        'Z5upctFT+syTbtip': < RobotCombatAvatarShootingRange(Z5upctFT + syTbtip) > ,
        'Z5upctFT+syTbtil': < RobotCombatAvatarShootingRange(Z5upctFT + syTbtil) > ,
        'Z5upctFT+syTbtiz': < RobotCombatAvatarShootingRange(Z5upctFT + syTbtiz) > ,
        'Z5upctFT+syTbtiu': < RobotCombatAvatarShootingRange(Z5upctFT + syTbtiu) > ,
        'Z5upctFT+syTbti5': < RobotCombatAvatarShootingRange(Z5upctFT + syTbti5) > ,
        'Z5upctFT+syTbti9': < RobotCombatAvatarShootingRange(Z5upctFT + syTbti9) > ,
        'Z5uqYdFT+syTbxiD': < Bomb(Z5uqYdFT + syTbxiD) >
    },
    'entity_category': defaultdict( < class 'dict' > , {
        'CombatAvatar': {
            'Z5uqYdFT+syTbxh8': < PlayerCombatAvatarShootingRange(Z5uqYdFT + syTbxh8) > ,
            'Z5upctFT+syTbtip': < RobotCombatAvatarShootingRange(Z5upctFT + syTbtip) > ,
            'Z5upctFT+syTbtil': < RobotCombatAvatarShootingRange(Z5upctFT + syTbtil) > ,
            'Z5upctFT+syTbtiz': < RobotCombatAvatarShootingRange(Z5upctFT + syTbtiz) > ,
            'Z5upctFT+syTbtiu': < RobotCombatAvatarShootingRange(Z5upctFT + syTbtiu) > ,
            'Z5upctFT+syTbti5': < RobotCombatAvatarShootingRange(Z5upctFT + syTbti5) > ,
            'Z5upctFT+syTbti9': < RobotCombatAvatarShootingRange(Z5upctFT + syTbti9) >
        },
        'CombatTeamEntity_ShootingRange': {
            'Z5uqYdFT+syTbxiB': < CombatTeamEntity_ShootingRange(Z5uqYdFT + syTbxiB) >
        },
        'PlayerCombatAvatarShootingRange': {
            'Z5uqYdFT+syTbxh8': < PlayerCombatAvatarShootingRange(Z5uqYdFT + syTbxh8) >
        },
        'GameLogicShootingRange': {
            'Z5upctFT+syTbtih': < GameLogicShootingRange(Z5upctFT + syTbtih) >
        },
        'RobotCombatAvatarShootingRange': {
            'Z5upctFT+syTbtip': < RobotCombatAvatarShootingRange(Z5upctFT + syTbtip) > ,
            'Z5upctFT+syTbtil': < RobotCombatAvatarShootingRange(Z5upctFT + syTbtil) > ,
            'Z5upctFT+syTbtiz': < RobotCombatAvatarShootingRange(Z5upctFT + syTbtiz) > ,
            'Z5upctFT+syTbtiu': < RobotCombatAvatarShootingRange(Z5upctFT + syTbtiu) > ,
            'Z5upctFT+syTbti5': < RobotCombatAvatarShootingRange(Z5upctFT + syTbti5) > ,
            'Z5upctFT+syTbti9': < RobotCombatAvatarShootingRange(Z5upctFT + syTbti9) >
        },
        'Bomb': {
            'Z5uqYdFT+syTbxiD': < Bomb(Z5uqYdFT + syTbxiD) >
        }
    }),
    'entity_show_model': < bound method Space.entity_show_model of < Space(Z5upctFT + syTbtig) >> ,
    'frame_delta': 0,
    'fsm_target_state': 'StateLoaded',
    'fsm_tick_func': None,
    'game_logic': < GameLogicShootingRange(Z5upctFT + syTbtih) > ,
    'get_gtick': < bound method Entity.get_gtick of < Space(Z5upctFT + syTbtig) >> ,
    'global_store_info': {},
    'high_value_effect_items': set(),
    'hud_scene_copy_enabled_reason': 0,
    'id': 'Z5upctFT+syTbtig',
    'init': < bound method Space.init of < Space(Z5upctFT + syTbtig) >> ,
    'init_from_dict': < bound method EntityMetaClass.replaceInitFromDict. < locals > .init_from_dict of < Space(Z5upctFT + syTbtig) >> ,
    'is_deactived': < bound method Entity.is_deactived of < Space(Z5upctFT + syTbtig) >> ,
    'is_destroyed': < bound method Entity.is_destroyed of < Space(Z5upctFT + syTbtig) >> ,
    'is_high_world': None,
    'is_in_hall': False,
    'is_loaded': < function ClientSpace.is_loaded at 0x78e5010040 > ,
    'is_moba_map': False,
    'is_relay': False,
    'is_replaying': False,
    'is_seamless_load': False,
    'is_si_island': False,
    'last_stutter_count': 23,
    'leave': < bound method Space.leave of < Space(Z5upctFT + syTbtig) >> ,
    'load': < bound method Space.load of < Space(Z5upctFT + syTbtig) >> ,
    'loaded_ticket': 'Z5uqrEIaqTAC3h7O',
    'loaded_timer': None,
    'loader': < gclient.framework.entities.space.SpaceLoader object at 0x784307da50 > ,
    'loading_start_checker': None,
    'loading_time': 0.4265444278717041,
    'logger': < Logger Space(DEBUG) > ,
    'observation_point_deadline': 0.0,
    'onEntityClassRegistered': < bound method Entity.onEntityClassRegistered of < class 'gclient.framework.entities.space.Space' >> ,
    'on_create_entity': < bound method Space.on_create_entity of < Space(Z5upctFT + syTbtig) >> ,
    'on_loaded': < bound method Space.on_loaded of < Space(Z5upctFT + syTbtig) >> ,
    'owner': < PlayerAvatar(A + pUrwUSaBFTuCIK) > ,
    'physics_shape_wrap': < PhysicsShapeWrapper object at 0x73fe32d280 > ,
    'physics_tick_inloop': False,
    'physics_tick_pending': [],
    'physics_tickers': set(),
    'pre_reload_script': < bound method Entity.pre_reload_script of < Space(Z5upctFT + syTbtig) >> ,
    'preload_pivot_clear_timer': -51,
    'prev_state': 'StateLoading',
    'proto': {
        'entrance_list': ((-16.621, 0.042, -6.784, 89.9), ),
        'name': 'Range',
        'id': 14,
        'map': 'shootingrange_test2'
    },
    'query_land_cache': {},
    'query_land_cache_hits': 0,
    'query_land_cache_ticker': -28,
    'query_land_cache_total': 0,
    'real_world_name': 'shootingrange_test2',
    'registry': {},
    'replay_game_logic_id': '',
    'replay_kind': 1,
    'reuse': < bound method Space.reuse of < Space(Z5upctFT + syTbtig) >> ,
    'script_lod_model_building_distance': 100,
    'script_lod_model_distance': 100,
    'script_lod_model_ticker': -31,
    'script_lod_models': {},
    'set_tick': < bound method Entity.set_tick of < Space(Z5upctFT + syTbtig) >> ,
    'setdefault': < bound method Entity.setdefault of < Space(Z5upctFT + syTbtig) >> ,
    'space_principle_role_mgr': < SpacePrincipleRoleMgr(0x0 x73fff14290) > ,
    'space_tick_inloop': False,
    'space_tick_pending': [],
    'space_tickers': set(),
    'spaceno': 14,
    'start_loading_time': 1738255020.3784173,
    'state': 'StateLoaded',
    'terrain': None,
    'terrain_inner': None,
    'tick': < bound method Entity.tick of < Space(Z5upctFT + syTbtig) >> ,
    'timer_check_python': None,
    'timer_live_timer': -79,
    'timer_log_elk': -77,
    'timer_log_qsec': -78,
    'uistage_type': 4,
    'weather_mgr': < gclient.util.weather_util.WeatherManager object at 0x73fff1c150 > ,
    'world': < IWorld object at 0x781b611400 > ,
    'world_ientity_building_dict': {},
    'world_ientity_dict': {},
    'world_name': 'shootingrange_test2',
    'world_preload_pivots': defaultdict( < class 'list' > , {}),
    'world_preload_pivots_deadline': defaultdict( < class 'float' > , {})
}