{
    'IsATM': False,
    'IsATMGuardAI': False,
    'IsAirDrop': False,
    'IsAmmoBox': False,
    'IsArrow': False,
    'IsAttackDrone': False,
    'IsAvatar': False,
    'IsBarrieCannon': False,
    'IsBomb': False,
    'IsBuilding': False,
    'IsChaosUav': False,
    'IsCombatAvatar': False,
    'IsCombatAvatarSniper': False,
    'IsCombatAvatarZombieXray': False,
    'IsCombatTeam': False,
    'IsCombatUnit': False,
    'IsContrabandPlane': False,
    'IsCrack': False,
    'IsCrow': False,
    'IsCureUav': False,
    'IsCureUavFix': False,
    'IsDestructible': False,
    'IsDummyCombatAvatar': False,
    'IsEmoteTree': False,
    'IsEnergyStronghold': False,
    'IsEntityAttach': False,
    'IsEntityMaster': False,
    'IsGameLogic': False,
    'IsGlass': False,
    'IsHelenAI': False,
    'IsHolographicRobot': False,
    'IsIceWall': False,
    'IsIgnoreCue': False,
    'IsItem': False,
    'IsItemSpaceSnare': False,
    'IsMagicField': False,
    'IsMonitorMissile': False,
    'IsMonster': False,
    'IsMovingPlatform': False,
    'IsObserveAvatar': False,
    'IsOccupyContractTarget': False,
    'IsOccupyContractTargetNew': False,
    'IsOilbox': False,
    'IsPhyBall': False,
    'IsPlayerCombatAvatar': False,
    'IsPlayerObserveAvatar': False,
    'IsPortableShop': False,
    'IsRPGMissile': False,
    'IsReplayPuppet': False,
    'IsReplayRecorder': False,
    'IsRobotCombatAvatar': False,
    'IsRobotCombatAvatarZombie': False,
    'IsSafeBox': False,
    'IsSaveDrone': False,
    'IsSaveMachine': False,
    'IsScoutArrow': False,
    'IsSearchContractBox': False,
    'IsShield': False,
    'IsShop': False,
    'IsSimpleCombatUnit': False,
    'IsSpellDrone': False,
    'IsStickyMaster': False,
    'IsStronghold': False,
    'IsStropUav': False,
    'IsSupply': False,
    'IsSwordSpirit': False,
    'IsSyncTransEntity': False,
    'IsSystemKiller': False,
    'IsVehicle': False,
    'IsVirtualInteractionEntity': False,
    'NinjaBeacon': False,
    '__class__': < class 'gclient.framework.entities.camera.Camera' > ,
    '__components__': [],
    '__dict__': {
        'space': < Space(Z5sh9jw2U1BjSHj9) > ,
        'controller': < CameraController object at 0x73f7e16000 > ,
        'collider': < TpsCollider object at 0x73f7e155c0 > ,
        'shaker': < CameraShaker object at 0x73f7e14cc0 > ,
        'placer': < gclient.framework.camera.fps_placer.FpsPlacer object at 0x73f77c7d50 > ,
        'target': < gclient.gameplay.logic_base.models.avatar_model.PlayerAvatarModel object at 0x780b2dac90 > ,
        'debug': False,
        'is_actived': True,
        'pre_placer_info': {
            'pre_cameraPosition': < -16.2063,
            1.5500,
            -8.2387 > ,
            'pre_direction': < -0.2432,
            0.0000,
            0.9700 >
        },
        'normal_placer': < gclient.framework.camera.fps_placer.FpsPlacer object at 0x73f77c7d50 > ,
        'special_placer': None,
        'camera_id': 0,
        'replay_mode': None,
        'look_around_pre_camera_id': 0,
        'checker': < CameraChecker object at 0x73f7e15480 > ,
        'sensors': < SensorPipe object at 0x73f7e15200 >
    },
    '__doc__': None,
    '__module__': 'gclient.framework.entities.camera',
    '__weakref__': None,
    'camera_id': 0,
    'checker': < CameraChecker object at 0x73f7e15480 > ,
    'collider': < TpsCollider object at 0x73f7e155c0 > ,
    'controller': < CameraController object at 0x73f7e16000 > ,
    'debug': False,
    'enableCollider': False,
    'engine_camera': < ICamera object at 0x73f7ea3b00 > ,
    'is_actived': True,
    'is_fps_avatar': False,
    'is_fps_placer': True,
    'is_free_placer': False,
    'is_gunsmith_placer': False,
    'is_look_around': False,
    'is_parachute_placer': False,
    'is_replay_avatar': False,
    'is_replay_room': False,
    'is_tfps_placer': True,
    'is_tps_placer': False,
    'look_around_pre_camera_id': 0,
    'normal_placer': < gclient.framework.camera.fps_placer.FpsPlacer object at 0x73f77c7d50 > ,
    'placer': < gclient.framework.camera.fps_placer.FpsPlacer object at 0x73f77c7d50 > ,
    'position': < -16.4215,
    1.5515,
    -7.1558 > ,
    'position_tuple': (-16.421533584594727, 1.5515000820159912, -7.155773162841797),
    'pre_direction': < -0.2432,
    0.0000,
    0.9700 > ,
    'pre_placer_info': {
        'pre_cameraPosition': < -16.2063,
        1.5500,
        -8.2387 > ,
        'pre_direction': < -0.2432,
        0.0000,
        0.9700 >
    },
    'replay_mode': None,
    'sensors': < SensorPipe object at 0x73f7e15200 > ,
    'shaker': < CameraShaker object at 0x73f7e14cc0 > ,
    'space': < Space(Z5sh9jw2U1BjSHj9) > ,
    'special_placer': None,
    'target': < gclient.gameplay.logic_base.models.avatar_model.PlayerAvatarModel object at 0x780b2dac90 >
}