{
    'CLIENT_PRIORITY_UNIT_STATE': ('Swim', 'ClimbLadder'),
    'EQUIPMENT_SUITABLE_SLOTS': {
        1: [1001, 1002],
        3: [1004],
        2: [1003],
        5: [1005],
        11: [3001, 3002],
        12: [3001, 3002],
        15: [5002],
        13: [4001, 4002],
        23: [4003]
    },
    'HAS_TOPLOGO': False,
    'IS_SHOOTING_RANGE': True,
    'IsATM': False,
    'IsATMGuardAI': False,
    'IsAirDrop': False,
    'IsAmmoBox': False,
    'IsArrow': False,
    'IsAttackDrone': False,
    'IsAvatar': False,
    'IsBarrieCannon': False,
    'IsBomb': False,
    'IsBuilding': False,
    'IsChaosUav': False,
    'IsCombatAvatar': True,
    'IsCombatAvatarSniper': False,
    'IsCombatAvatarZombieXray': False,
    'IsCombatTeam': False,
    'IsCombatUnit': True,
    'IsContrabandPlane': False,
    'IsCrack': False,
    'IsCrow': False,
    'IsCureUav': False,
    'IsCureUavFix': False,
    'IsDestructible': False,
    'IsDummyCombatAvatar': False,
    'IsEmoteTree': False,
    'IsEnergyStronghold': False,
    'IsEntityAttach': False,
    'IsEntityMaster': False,
    'IsGameLogic': False,
    'IsGlass': False,
    'IsHelenAI': False,
    'IsHolographicRobot': False,
    'IsIceWall': False,
    'IsIgnoreCue': False,
    'IsItem': False,
    'IsItemSpaceSnare': False,
    'IsMagicField': False,
    'IsMonitorMissile': False,
    'IsMonster': False,
    'IsMovingPlatform': False,
    'IsObserveAvatar': False,
    'IsOccupyContractTarget': False,
    'IsOccupyContractTargetNew': False,
    'IsOilbox': False,
    'IsPhyBall': False,
    'IsPlayerCombatAvatar': True,
    'IsPlayerObserveAvatar': False,
    'IsPortableShop': False,
    'IsRPGMissile': False,
    'IsReplayPuppet': False,
    'IsReplayRecorder': False,
    'IsRobotCombatAvatar': False,
    'IsRobotCombatAvatarZombie': False,
    'IsSafeBox': False,
    'IsSaveDrone': False,
    'IsSaveMachine': False,
    'IsScoutArrow': False,
    'IsSearchContractBox': False,
    'IsShield': False,
    'IsShop': False,
    'IsSimpleCombatUnit': True,
    'IsSpellDrone': False,
    'IsStickyMaster': False,
    'IsStronghold': False,
    'IsStropUav': False,
    'IsSupply': False,
    'IsSwordSpirit': False,
    'IsSyncTransEntity': False,
    'IsSystemKiller': False,
    'IsVehicle': False,
    'IsVirtualInteractionEntity': False,
    'IsVisible': True,
    'NEED_BESHOOT_FRESNEL': False,
    'NinjaBeacon': False,
    'Pickup_Equip_Type_Map': {
        1: 'Gun',
        11: 'Throwable',
        12: 'Throwable',
        14: 'Support',
        16: 'Emergency_Needle',
        17: 'Medicine'
    },
    'Pickup_Item_Type_Map': {
        101: 'Equip',
        102: 'Ammo',
        105: 'Coin',
        109: 'Genecode',
        112: 'BrokenTalentCore',
        116: 'TacticalEnergy',
        117: 'Coin'
    },
    'TOPLOGO_SHOW_POSITION': True,
    '__class__': < class 'gclient.gameplay.logic_shootingrange.combat_avatar_shootingrange.PlayerCombatAvatarShootingRange' > ,
    '__components__': [ < class 'gclient.gameplay.logic_base.entities.combatavatarmembers.cimp_anti_plugin.PlayerCombatAvatarMember' > , < class 'gclient.gameplay.logic_base.comps.comp_beard.PlayerCombatAvatarMember' > , < class 'gclient.gameplay.logic_base.comps.comp_parachute.ParaPlayerCombatAvatarMemberBase' > , < class 'gclient.gameplay.logic_base.entities.combatavatarmembers.cimp_bomb.PlayerCombatAvatarMember' > , < class 'gclient.gameplay.logic_base.entities.combatavatarmembers.cimp_vehicle.CombatAvatarMember' > , < class 'gclient.gameplay.logic_base.entities.combatavatarmembers.cimp_house_detector.PlayerCombatAvatarMember' > , < class 'gclient.gameplay.logic_base.entities.combatavatarmembers.cimp_emote.PlayerCombatAvatarMember' > , < class 'gclient.gameplay.logic_base.entities.combatavatarmembers.cimp_attach_model.PlayerCombatAvatarMember' > , < class 'gclient.gameplay.logic_base.entities.combatavatarmembers.cimp_third_mode_logic.CombatAvatarMember' > , < class 'gclient.gameplay.logic_base.entities.combatavatarmembers.cimp_combat_cc.PlayerCombatAvatarMember' > , < class 'gclient.gameplay.logic_base.entities.combatavatarmembers.cimp_space.PlayerCombatAvatarMember' > , < class 'gclient.gameplay.logic_base.entities.combatavatarmembers.cimp_buff.PlayerCombatAvatarMember' > , < class 'gclient.gameplay.logic_base.entities.combatavatarmembers.cimp_swim.PlayerCombatAvatarMember' > , < class 'gclient.gameplay.logic_base.entities.combatavatarmembers.cimp_model.PlayerCombatAvatarMember' > , < class 'gclient.gameplay.logic_base.entities.combatavatarmembers.cimp_building.PlayerCombatAvatarMember' > , < class 'gclient.gameplay.logic_base.entities.combatavatarmembers.cimp_pickup.PlayerCombatAvatarMember' > , < class 'gclient.gameplay.logic_base.entities.combatavatarmembers.cimp_help.PlayerCombatAvatarMember' > , < class 'gclient.gameplay.logic_base.entities.combatavatarmembers.cimp_talent.PlayerCombatAvatarMember' > , < class 'gclient.gameplay.logic_base.entities.combatavatarmembers.cimp_moving_platform.PlayerCombatAvatarMember' > , < class 'gclient.gameplay.logic_base.entities.combatavatarmembers.cimp_gyroscope.PlayerCombatAvatarMember' > , < class 'gclient.gameplay.logic_base.entities.combatavatarmembers.cimp_control_target.PlayerCombatAvatarMember' > , < class 'gclient.gameplay.logic_base.entities.combatavatarmembers.cimp_state_relationship.PlayerCombatAvatarMember' > , < class 'gclient.gameplay.logic_base.entities.combatavatarmembers.cimp_combat_attr.PlayerCombatAvatarMember' > , < class 'gclient.gameplay.logic_base.entities.combatavatarmembers.cimp_combat.PlayerCombatAvatarMember' > , < class 'gclient.gameplay.logic_base.entities.combatavatarmembers.cimp_combat_item.PlayerCombatAvatarMember' > , < class 'gclient.gameplay.logic_base.entities.combatavatarmembers.cimp_input_controller_handle.PlayerCombatAvatarMember' > , < class 'gclient.gameplay.logic_base.entities.combatavatarmembers.cimp_story_tick.PlayerCombatAvatarMember' > , < class 'gclient.gameplay.logic_base.entities.combatavatarmembers.cimp_combat_antiplugin.PlayerCombatAvatarMember' > , < class 'gclient.gameplay.logic_base.entities.combatavatarmembers.cimp_profile.PlayerCombatAvatarMember' > , < class 'gclient.gameplay.logic_base.entities.combatavatarmembers.cimp_sound.PlayerCombatAvatarMember' > , < class 'gclient.gameplay.logic_base.entities.combatavatarmembers.cimp_store.CombatAvatarMember' > , < class 'gclient.gameplay.logic_base.entities.combatavatarmembers.cimp_combat_unit.PlayerCombatAvatarMember' > , < class 'gclient.gameplay.logic_base.entities.combatavatarmembers.cimp_item.PlayerCombatAvatarMember' > , < class 'gclient.gameplay.logic_base.entities.combatavatarmembers.cimp_snare.PlayerCombatAvatarMember' > , < class 'gclient.gameplay.logic_base.entities.combatavatarmembers.cimp_world_field.PlayerCombatAvatarMember' > , < class 'gclient.gameplay.logic_base.entities.combatavatarmembers.cimp_client_buff.PlayerCombatAvatarMember' > , < class 'gclient.gameplay.logic_base.entities.combatavatarmembers.cimp_effect.PlayerCombatAvatarMember' > , < class 'gclient.gameplay.logic_base.entities.combatavatarmembers.cimp_execute.PlayerCombatAvatarMember' > , < class 'gclient.gameplay.logic_base.entities.combatavatarmembers.cimp_backpack.PlayerCombatAvatarMember' > , < class 'gclient.gameplay.logic_base.entities.combatavatarmembers.cimp_store.PlayerCombatAvatarMember' > , < class 'gclient.gameplay.logic_base.entities.combatavatarmembers.cimp_building.CombatAvatarMember' > , < class 'gclient.gameplay.logic_base.entities.combatavatarmembers.cimp_vehicle.PlayerCombatAvatarMember' > , < class 'gclient.gameplay.logic_base.entities.combatavatarmembers.cimp_drone.PlayerCombatAvatarMember' > , < class 'gclient.gameplay.logic_base.entities.combatavatarmembers.cimp_kick_up.PlayerCombatAvatarMember' > , < class 'gclient.gameplay.logic_base.entities.combatavatarmembers.cimp_report.PlayerCombatAvatarMember' > , < class 'gclient.gameplay.logic_base.entities.combatavatarmembers.cimp_spell.PlayerCombatAvatarMember' > , < class 'gclient.gameplay.logic_base.entities.combatavatarmembers.cimp_graph_cue.PlayerCombatAvatarMember' > , < class 'gclient.gameplay.logic_base.entities.combatavatarmembers.cimp_motion.PlayerCombatAvatarMember' > , < class 'gclient.gameplay.logic_base.entities.combatavatarmembers.cimp_assist_aim.PlayerCombatAvatarMember' > , < class 'gclient.gameplay.logic_base.entities.combatavatarmembers.cimp_combat_log.PlayerCombatAvatarMember' > , < class 'gclient.gameplay.logic_base.entities.combatavatarmembers.cimp_calculation.PlayerCombatAvatarMember' > , < class 'gclient.gameplay.logic_base.entities.combatavatarmembers.cimp_auto_fire.PlayerCombatAvatarMember' > , < class 'gclient.gameplay.logic_base.entities.combatavatarmembers.cimp_sticky_master.CombatAvatarMember' > , < class 'gclient.gameplay.logic_base.entities.combatavatarmembers.cimp_input_controller.PlayerCombatAvatarMember' > , < class 'gclient.gameplay.logic_base.entities.combatavatarmembers.cimp_replay.PlayerCombatAvatarMember' > , < class 'gclient.gameplay.logic_base.comps.comp_compatible.PlayerCombatAvatarMember' > , < class 'gclient.gameplay.logic_base.comps.comp_hero.PlayerCombatAvatarMember' > , < class 'gclient.gameplay.logic_base.comps.comp_talent.PlayerCombatAvatarMember' > , < class 'gclient.gameplay.logic_shootingrange.avatarmembers.cimp_input_controller.PlayerCombatAvatarMember' > , < class 'gclient.gameplay.logic_base.comps.comp_mark.PlayerCombatAvatarMember' > ],
    '__dict__': {
        '_is_deactive': False,
        '_is_destroyed': False,
        'id': 'Z5siQjw2U1BjSI8w',
        '_timers': {
            -56: < bound method CombatAvatarMember.TickUpdateSoundCache of < PlayerCombatAvatarShootingRange(Z5siQjw2U1BjSI8w) >> ,
            -57: < bound method PlayerCombatAvatarMember.OnClientBuffTick of < PlayerCombatAvatarShootingRange(Z5siQjw2U1BjSI8w) >> ,
            -58: < bound method PlayerCombatAvatarMember.ScaleEffectTimer of < PlayerCombatAvatarShootingRange(Z5siQjw2U1BjSI8w) >> ,
            -59: < bound method PlayerCombatAvatarMember.ReplayOnUploadCamera of < PlayerCombatAvatarShootingRange(Z5siQjw2U1BjSI8w) >> ,
            -60: < bound method PlayerCombatAvatarMember.ReplayOnFpsVarianceTick of < PlayerCombatAvatarShootingRange(Z5siQjw2U1BjSI8w) >> ,
            -61: < bound method PlayerCombatAvatarMember.TickCalcDistance of < PlayerCombatAvatarShootingRange(Z5siQjw2U1BjSI8w) >> ,
            -81: < built - in method clear of dict object at 0x781c958cc0 > ,
            -93: < built - in method clear of dict object at 0x7803bc2480 > ,
            -103: < built - in method clear of dict object at 0x78040c8dc0 > ,
            -104: < built - in method clear of dict object at 0x78040c9700 >
        },
        '_tick_timer': 0,
        'server': < client.AsioServerProxy.AsioServerProxy object at 0x7803544650 > ,
        '_space': < Space(Z5sh9jw2U1BjSHj9) > ,
        '_sky_sound_id': None,
        '_sky_sound_playing_id': None,
        'trainer_info': '',
        'trainee_info': [],
        '_is_cinematics': False,
        '_open_close_parachute_time': 0,
        'sky_process_timer': None,
        'use_camera_fps_for_para': True,
        '_para_check_stuck_timer': None,
        '_para_check_stuck_count': 0,
        '_para_check_stuck_pre_pos': None,
        '_high_sky_client_para_stage': None,
        'is_player_set_camera': False,
        'freefall_start_height': -100,
        'throw_item_guid': '',
        '_is_in_house': False,
        '_enter_house_name': '',
        '_enter_house_count': 0,
        '_enter_house_range_name': '',
        '_enter_house_range_count': 0,
        '_house_range_timer': None,
        '_house_range_head_cover': False,
        'can_shoot_player_for_sound': False,
        'emitter_obstruct': 0,
        '_last_house_enter_trigger_name': None,
        'emote_detect_timer': None,
        'emote_hide_targets': [],
        'emote_log_dict': {},
        'delay_emote_timer': None,
        'attach_model_dict': {},
        'hero_skin_effects': [],
        'tps_show_entities': [],
        '_speak_eids': [],
        '_cc_speaking_timer': None,
        '_cc_nearby_timer': None,
        'cc_speak_channel': 0,
        'cc_voice_channel': 0,
        '_kill_ridicule_timer': None,
        '_hall_team_shield_ids': {},
        '_close_cc_timer_map': {},
        'rage_model_effect_id': None,
        'follow_entity': None,
        'buff_camera_effect_tmp': {},
        'water_height': -150,
        'water_trigger_id_list': [],
        'before_swim_weapon_guid': '',
        'check_swim_state_timer': None,
        'model': < gclient.gameplay.logic_base.models.avatar_model.PlayerAvatarModel object at 0x7803718850 > ,
        'model_loaded': True,
        'hand_model': < gclient.gameplay.logic_base.models.hand_model.HandModel object at 0x7803718050 > ,
        'trigger_inner_ids': [],
        'trigger_vehicle_counts': {},
        'door_building_owner_map': {},
        'sprint_door': None,
        'cache_enter_trigger_items': {},
        'trigger_items_timer': 0,
        'distance_from_camera': 0.0,
        'distance_fps_upper': 35.0,
        'distance_fps_floor': 5.0,
        'distance_fps_max_dist': 125.0,
        'degree_fps_upper': 25.0,
        'degree_fps_floor': 5.0,
        'nearby_combat_items': set(),
        'valid_trigger_entity_list': [],
        'target_trigger_entity': None,
        'teammate_xray_hidden_reason': 0,
        'trigger_supply_auto_open_timer': None,
        'pc_pick_mgr': None,
        'cur_focus_item': None,
        'cur_focus_item_pos': None,
        'cur_focus_box_guid': None,
        'is_help_by_uav': False,
        'is_gyroscope_reverse': True,
        'gyroscope': < gclient.framework.util.gyroscope.GyroscopePoseCombat object at 0x78037f1b90 > ,
        'gyroscope_sens_by_state': 2.0,
        'gyroscope_mode': 1,
        'gyroscope_switch_mode': 1,
        'gyroscope_horizontal_reverse': 0,
        'gyroscope_vertical_reverse': 0,
        'gyroscope_input_cut_off': 0.05,
        'total_reset_sensor_times': 0,
        'controlled_target_id': None,
        'state_relationship_set': {
            'EnterAds',
            'Idle'
        },
        'state_relationship_cache': {
            (12, ('Idle', )): (3, None),
            (19, ('Idle', )): (3, None)
        },
        'weapon_attr_cache': {},
        'combat_status_timestamps': {},
        'uav_start_time': None,
        'red_pack_msg': [],
        'forbid_auto_pickup_time_map': {
            'all': 0.0
        },
        'waiting_pickup_count_map': {},
        'container_show_set': set(),
        'check_item_timer': None,
        'check_door_trigger': None,
        'pickup_item_ticker': None,
        '_auto_mark_item_guid': None,
        '_auto_mark_item_timer': {},
        'scaned_talent_item': None,
        'total_pickup_data_pc_check': {},
        'med_sel_rid': 0,
        'med_last_offset_y': 0,
        'throwable_sel_rid': 0,
        'throwable_last_offset_y': 0,
        'emote_sel_rid': 0,
        'story_tick_funcs': [ < bound method PlayerCombatAvatarMember.UpdateInvisibleAvatarsFrameLimit of < PlayerCombatAvatarShootingRange(Z5siQjw2U1BjSI8w) >> , < bound method PlayerCombatAvatarMember.TickDealSpellResultRpc of < PlayerCombatAvatarShootingRange(Z5siQjw2U1BjSI8w) >> , < bound method PlayerCombatAvatarMember.ReplayOnPackTick of < PlayerCombatAvatarShootingRange(Z5siQjw2U1BjSI8w) >> , < bound method PlayerCombatAvatarMember.RaycastForMovingPlatform of < PlayerCombatAvatarShootingRange(Z5siQjw2U1BjSI8w) >> , < bound method GyroscopePoseCombat.GyroscopeTick of < gclient.framework.util.gyroscope.GyroscopePoseCombat object at 0x78037f1b90 >> ],
        'assassinate_effect_id': None,
        'calc_distance_diff_timer': -61,
        'last_position': (-16.621000289916992, 0.04200005531311035, -6.783999919891357),
        'last_crouch2_position': None,
        'distance_walk': 0,
        'distance_crouch2': 0,
        'distance_vehicle': 17.952216285326806,
        'low_fps_check': < gclient.framework.util.low_fps_util.LowFpsCheck object at 0x7803719910 > ,
        'sound_dict': {
            6: 5,
            4: 12
        },
        'sound_tag_dict': defaultdict( < class 'list' > , {
            'AdsUp': [(4, 12)]
        }),
        'sync_sound_dict': {},
        'broadcast_sound_limiter': defaultdict( < class 'float' > , {}),
        'broadcast_sound_interval': 0.25,
        'switch_dict_cache': {
            6: {
                'expired': 1738220340.9891925,
                'switch_dict': {
                    'visual': 'first',
                    'gun_type': 'm4a1'
                }
            },
            4: {
                'expired': 1738220343.2865322,
                'switch_dict': {
                    'visual': 'first',
                    'gun_type': 'm4a1'
                }
            }
        },
        'switch_dict_cache_timeout': 0.5,
        '_sound_tips_ban_reason': 0,
        'bomb_contact_entity': None,
        '_be_shoot_tech_effect_timer': None,
        'armor_recovering': False,
        'armor_effect': None,
        'extra_armor_effect': None,
        'extra_max_armor_effect': None,
        '_combat_team': < CombatTeamEntity_ShootingRange(Z5siQjw2U1BjSI81) > ,
        'bomb_path_effect': None,
        'tmp_forbidden_create_bomb_effect': False,
        'ig_voice_mgr': < gclient.gameplay.util.ig_voice_manager.IgVoiceManager object at 0x7803719850 > ,
        'path_queryer': {},
        'hold_item_timer': None,
        'snare_dict': {},
        'world_fields': [(6, 'Z5siQjw2U1BjSI8w')],
        'cur_active_world_field_id': 6,
        'sky_render_switcher': None,
        'sky_fade_time_zero': False,
        'scale_effects': {},
        'scale_effect_timer': -58,
        '_execute_event_id': None,
        'execute_player_pre_pos': None,
        '_execute_third_model': None,
        'nearby_dying_enemies': [],
        'cur_target_execute_id': None,
        '_execute_hide_ui_timer': None,
        '_last_execute_cancel_time': 0,
        '_last_execute_begin_time': 0,
        'execute_dissolving_entities': [],
        'next_weapon_guid': '',
        'next_spec_weapon_guid': '',
        'next_lefthand_weapon_guid': '',
        'ammos_for_cur_guns': {
            8,
            7
        },
        'client_ammo_update_timer': None,
        'client_left_ammo_update_timer': None,
        'scan_score_timer': None,
        '_sound_scan_core_event': None,
        'is_fast_raise_weapon': True,
        'gun_fire_timestamp': 0,
        'dual_gun_fire_timestamp': 0,
        'pre_weapon_slot': 1001,
        'teammate_backpack_usages': defaultdict( < class 'dict' > , {}),
        'delay_switch_weapon': 0,
        'delay_check_weapon_timer': None,
        'CLIENT_PRIORITY_UNIT_STATE': ('Swim', 'ClimbLadder'),
        'last_weapon_guid': '',
        'personal_store_data': None,
        'send_ig_request_chat_cd': 1738220339.9895895,
        'send_ig_request_chat_count': 0,
        'send_ig_request_chat_support_cd': 1738220339.9895935,
        'send_ig_request_chat_support_count': 0,
        'airdrop_store_near': set(),
        '_lean_out_check_valid_timer': None,
        'detached_from_vehicle': True,
        'controlling_drone_id': None,
        'is_drone_connect_loading_finished': True,
        'drone_init_pos': None,
        'is_knocking': False,
        'heartbeat_start_timer': None,
        'heartbeat_end_timer': None,
        'heartbeat_reset_timer': None,
        'heartbeat_delay_start_timer': None,
        'heartbeat_endtime': None,
        'heartbeat_num': 0,
        'heartbeat_avatar_cache_info': {},
        'heartbeat_spell_state': 0,
        'prone_for_forbidden_ads': False,
        'cure_uav_effect': None,
        'place_explode_entity': None,
        'place_paranoia_guids': [],
        'firewall_mode': 0,
        'place_firewall_effects': [],
        'wallbomb_mode': 0,
        'missile_indicate_effect_id': None,
        'missile_indicate_pos': None,
        'missile_indicate_tick': None,
        'cold_fields': {},
        'place_entity_guid': None,
        'place_entity_rotate': 0,
        'camera_effect_ids': {},
        'camera_effect_timers': {},
        '_is_ads': True,
        'light_attack_mode': False,
        'ballistic_effect_history': defaultdict( < class 'float' > , {}),
        'invalid_trans': << 1.0000,
        0.0000,
        0.0000 > < 0.0000,
        1.0000,
        0.0000 > < 0.0000,
        -0.0000,
        1.0000 > < 0.0000,
        -2000.0000,
        0.0000 >> ,
        'electical_proto': None,
        'hold_effect_id': None,
        'cannon_entity': None,
        'client_parkour': 0,
        'cure_uav_camera_effect': None,
        'is_using_nova_second_skill': False,
        'samurai_sprint_start_time': 0,
        'samurai_sprint_tick': 0,
        'samurai_sprint_effect_id': 0,
        'samurai_sprint_pos': None,
        'cure_connect_line_effect_info': None,
        'cur_shield_magic_field_id': None,
        'force_cure_self': False,
        'last_shoot_idx': -1,
        'shoot_idx': 0,
        'shoot_immediately': True,
        '_delay_shoot_reason': 0,
        'dual_shoot_immediately': True,
        '_delay_dual_shoot_reason': 0,
        'is_shoot_breaking': False,
        'is_fire_by_right': False,
        'fire_by_right_timestamp': 0,
        'fireend_by_right_timestamp': 0,
        'is_fire_by_left': False,
        'fire_by_left_timestamp': 0,
        'fireend_by_left_timestamp': 0,
        'try_fire_start': False,
        'try_dual_fire_start': False,
        '_try_enter_ads': False,
        '_is_real_ads': True,
        '_is_shooting': False,
        '_is_dual_shooting': False,
        '_is_ammo_reloading': False,
        'is_enter_ads_by_fire': False,
        'force_no_fall_hurt': False,
        'refresh_observe_timer': None,
        'camera_id_before_ads': None,
        'light_attack_pos': None,
        'break_use_medicine': False,
        'light_attack_range_eid': None,
        'reload_fire_interval_timer': None,
        'reload_dual_fire_interval_timer': None,
        'shoot_rescue_timer': None,
        'dual_shoot_rescue_timer': None,
        'sprint_rb': None,
        'cannon_pre_place_effect': None,
        'disable_signal': {
            32,
            3,
            6,
            7,
            8,
            16,
            54,
            23,
            25
        },
        '_fps_mode': True,
        '_is_sprint': False,
        '_is_super_sprint': False,
        '_is_auto_sprint': False,
        '_is_auto_supersprint': False,
        '_pose_type': 0,
        'last_move_dir': 1,
        'move_dir': 0,
        'last_speed_level': 1,
        'last_jump_timestamp': 1738220340.382635,
        'last_crouch_timestamp': 0,
        'last_prone_timestamp': 0,
        'last_creep_up_timestamp': 0,
        'last_slide_timestamp': 0,
        'exit_slide_timestamp': 0,
        '_move_action_speed': 1.0,
        'jump_top_height': -100,
        'is_slide_to_end': False,
        'prone_is_ads': False,
        'prone_end_for_crouch': False,
        'prone_slope_timer': None,
        '_prone_check_index': 0,
        '_prone_check_name': None,
        'enable_slope': True,
        'is_in_air': False,
        'can_high_sky_para': False,
        'can_para_after_samurai_sprint': False,
        'tell_server_motion_state': 'Idle',
        'block_need_slow_down': True,
        'assist_aim_cls': {
            5: < class 'gclient.framework.util.assist_aim_util.AssistAimMelee' > ,
            20: < class 'gclient.framework.util.assist_aim_util.AssistAimTracingTargetNoSearching' > ,
            21: < class 'gclient.framework.util.assist_aim_util.AssistAimAndShootTracingNoSearching' >
        },
        'assist_aims': {
            5: < gclient.framework.util.assist_aim_util.AssistAimMelee object at 0x780371ac10 > ,
            20: < gclient.framework.util.assist_aim_util.AssistAimTracingTargetNoSearching object at 0x7804058650 > ,
            21: < gclient.framework.util.assist_aim_util.AssistAimAndShootTracingNoSearching object at 0x7804059590 >
        },
        'sensitivity_factor': 5e-05,
        'sens_factor': 1.0,
        'sensitivity_x': 0.003096872,
        'sensitivity_y': 0.003096872,
        'check_aim_enemy_timer': None,
        'check_aim_enemy_interval': 0.2,
        'aiming_enemy_id': '',
        'check_aim_enemy_ref': 0,
        '_assist_aim_ban_reason': 0,
        'magic_bullet_lock_target': None,
        'magic_bullet_shoot_miss_count': 0,
        'target_sensitivity_x': 0.003096872,
        'target_sensitivity_y': 0.003096872,
        'previous_sensitivity_x': 0.004,
        'previous_sensitivity_y': 0.004,
        'sensitivity_lerp_duration': 0,
        'sensitivity_lerp_elapsed': 0,
        'controller_sensitivity_x': 0.0018581232,
        'controller_sensitivity_y': 0.0018581232,
        'target_controller_sensitivity_x': 0.0018581232,
        'target_controller_sensitivity_y': 0.0018581232,
        'previous_controller_sensitivity_x': 0.0024,
        'previous_controller_sensitivity_y': 0.0024,
        'combat_log_dict': {
            'CombatGunFireLog': {}
        },
        'is_fire_manually': False,
        'fsm_auto_fire': None,
        'fsm_auto_fire_timer': None,
        'jump_begin_time': 0,
        'sprint_begin_time': 0,
        'inspection_timer': None,
        'auto_sprint_timer': None,
        'throwable_timer': None,
        'cur_sel_throwable_item_guid': None,
        'is_selecting_throwable': False,
        'medicine_timer': None,
        'cur_sel_medicine_item_guid': None,
        'is_selecting_medicine': False,
        'cur_sel_emote': -1,
        'window_height_2': 540.0,
        'window_width_2': 1200.0,
        'emote_cancel_range': 10000,
        'give_up_timer': None,
        'skill_weapon_down_time': 0,
        'smart_f_funcs': [( < bound method PlayerCombatAvatarMember.GetSmartFPos_PickUp of < PlayerCombatAvatarShootingRange(Z5siQjw2U1BjSI8w) >> , < bound method PlayerCombatAvatarMember.DoSmartF_PickUp_Down of < PlayerCombatAvatarShootingRange(Z5siQjw2U1BjSI8w) >> , < bound method PlayerCombatAvatarMember.DoSmartF_PickUp_Up of < PlayerCombatAvatarShootingRange(Z5siQjw2U1BjSI8w) >> ), ( < bound method PlayerCombatAvatarMember.GetSmartFPos_InteractiveUIAction of < PlayerCombatAvatarShootingRange(Z5siQjw2U1BjSI8w) >> , < bound method PlayerCombatAvatarMember.DoSmartF_InteractiveUIAction_Down of < PlayerCombatAvatarShootingRange(Z5siQjw2U1BjSI8w) >> , < bound method PlayerCombatAvatarMember.DoSmartF_InteractiveUIAction_Up of < PlayerCombatAvatarShootingRange(Z5siQjw2U1BjSI8w) >> )],
        'wait_f_up_func': None,
        'pick_up_box_timer': None,
        'hand_model_status_cache': {},
        'hand_model_status_statistic': defaultdict( < class 'int' > , {}),
        'hand_model_status_hits': 0,
        'hand_model_status_total': 0,
        'hand_model_status_last': '',
        '_rhs': {},
        'replay_camera_stream': [],
        'replay_camera_stamp': 1738220343.511303,
        'replay_camera_expired': 0.0,
        'replay_rpc_stream': [],
        'last_camera_frame': [430, -94, 896, 0, 5000, 4000, 0, 0],
        'replay_on_upload_camera_timer': -59,
        'replay_fps_variance_timer': -60,
        'replay_upload_assist_timer': None,
        'replay_assist_inputs_stamp': 1738220339.9899285,
        'camera_date_getters': {
            0: < bound method PlayerCombatAvatarMember._GetCameraData_TPS of < PlayerCombatAvatarShootingRange(Z5siQjw2U1BjSI8w) >> ,
            1: < bound method PlayerCombatAvatarMember._GetCameraData_FPS of < PlayerCombatAvatarShootingRange(Z5siQjw2U1BjSI8w) >> ,
            2: < bound method PlayerCombatAvatarMember._GetCameraData_TPS of < PlayerCombatAvatarShootingRange(Z5siQjw2U1BjSI8w) >> ,
            3: < bound method PlayerCombatAvatarMember._GetCameraData_AIM of < PlayerCombatAvatarShootingRange(Z5siQjw2U1BjSI8w) >> ,
            4: < bound method PlayerCombatAvatarMember._GetCameraData_DEATH of < PlayerCombatAvatarShootingRange(Z5siQjw2U1BjSI8w) >> ,
            5: < bound method PlayerCombatAvatarMember._GetCameraData_FREE of < PlayerCombatAvatarShootingRange(Z5siQjw2U1BjSI8w) >> ,
            6: < bound method PlayerCombatAvatarMember._GetCameraData_CamCtrl of < PlayerCombatAvatarShootingRange(Z5siQjw2U1BjSI8w) >> ,
            7: < bound method PlayerCombatAvatarMember._GetCameraData_Emote of < PlayerCombatAvatarShootingRange(Z5siQjw2U1BjSI8w) >> ,
            8: < bound method PlayerCombatAvatarMember._GetCameraData_TPS of < PlayerCombatAvatarShootingRange(Z5siQjw2U1BjSI8w) >>
        },
        'client_spectator_camera_stream': [],
        'ads_shield_effect': None,
        'ads_shield_timer': None,
        'fsm_ads_mark_pos': None,
        'ads_mark_pos_avatars': [],
        'feel_hp_timer': None,
        'low_hp_effect_timer': None,
        'expose_killed_enemy_pos_timer': None,
        '_crisis_aware_ticker': None,
        '_crisis_aware_see_info': {},
        'feel_surmount1_timer': None,
        'feel_surmount1_stamp': 1738220339.9899697,
        'feel_surmount1_id': '',
        '_holographic_mark_entities': {},
        'mark_toplogo_dict': {},
        'common_mark_dict': {
            'Z5sjNEIaqXd2RUYA': < gclient.framework.commoncomps.common_toplogo.ToplogoGunRefit object at 0x7803b32910 >
        },
        'common_mark_info': {
            'Z5sjNEIaqXd2RUYA': {
                'camera_hit_min_opacity': 70,
                'offset': (1, 2.5, 0),
                'cls': 'ToplogoGunRefit',
                'visible_distance': 50.0,
                'camera_hit_max_dis': 165,
                'camera_hit_max_opacity': 255,
                'min_opacity': 1.0,
                'id': 10,
                'camera_hit': False,
                'icon': 733,
                'max_opacity': 1.0,
                'camera_hit_min_dis': 50,
                'fov_distance': 10.0,
                'pos': (-23.85, 0, -6.73),
                'scene_on': True
            }
        },
        'common_center_mark_dict': {},
        'assist_mark': < gclient.framework.util.assist_aim_util.AssistMark object at 0x780371a9d0 > ,
        'gun_spell_mark_enemy_stamp': None,
        'gun_spell_last_mark_enemy': None,
        'cur_mark_mission_guid': '',
        'mark_toplogo_op_mode': 0,
        'mark_toplogo_hit_type': 1,
        'mark_toplogo_hit_guid': '',
        'mark_effect_dict': {},
        'is_refuse_team_mark': False,
        'cur_mark_avt_id': None,
        'anti_penetrate_draw_paths': [],
        'supply_dict': {},
        'update_around_items_timer': None,
        'highlight_item_guids': set(),
        'is_unfold_container': False,
        'is_unfold_main_pickup': True,
        'space_snare_update_cache': None,
        'highlight_around_items_timer': None,
        'auto_pickup_delay': False,
        'total_pickup_item': {},
        'total_pickup_data': {
            'nearby': {
                'id': 'nearby',
                'title': 'Nearby',
                'data': [],
                'priority': 0,
                'item_entity': None
            }
        },
        'total_pickup_data_sort': [{
            'id': 'nearby',
            'title': 'Nearby',
            'data': [],
            'priority': 0,
            'item_entity': None
        }],
        'pickup_group_box_ids': [],
        'has_recommend_item': False,
        'sound_cache_is_own_gun': True,
        'sound_cache_is_compound_bow': False,
        'sound_cache_gun_sound_media': 'm4a1_media',
        'sound_cache_max_gun_dist': 125,
        'sfx_cache_max_gun_dist': 125,
        'sound_cache_gun_direction': < 0.4771,
        -0.0000,
        0.9911 > ,
        'sound_cache_is_slient': 0.0,
        'sound_cache_gun_param_dict': {
            'roof_obstruct': 1,
            'in_same_room': 1
        },
        'sound_cache_is_friend': True,
        'auto_send_interval_last_yaw': 0.0,
        'auto_send_interval_last_pos': (0, 0, 0),
        'auto_send_interval_duration': 0.0,
        'weapon_guid_before_dying': '',
        'client_buff_ticker': -57,
        'ssp_recover_speed': 0.1,
        'ssp_use_speed': 0.2,
        'super_sprint_duration': 0.0,
        '_spell_result_cache': [],
        'toplogo_not_in_hide_state_enemy': set(),
        'replay_last_valid_pos': (-16.4495792388916, 0.05000007525086403, -7.268758296966553),
        'replay_upload_camera_interval': 0.02177576906979084,
        'xdroid_buy_callback': None,
        'last_support_item_id': '',
        'item_fsms': {},
        'cur_item_guid': '',
        'last_ask_help_time': 0,
        'force_use_client_pos': False,
        'last_server_pos_stamp': 0,
        'last_server_pos_time': 0,
        'last_server_position': None,
        'last_server_count': 0,
        '__limitcd_SendInputControllerImp': 1738220341.1069617,
        'recon_drone_frame_top_logo': None,
        'recon_drone_mark_ent_ids': set(),
        'team_val_recon_drone_id': None
    },
    '__doc__': None,
    '__limitcd_SendInputControllerImp': 1738220341.1069617,
    '__module__': 'gclient.gameplay.logic_shootingrange.combat_avatar_shootingrange',
    '__property_all__': {
        'name': '',
        'show_name': '',
        'anchor': 0,
        'cur_titles': < class 'gshare.ititle.NoPersistentTitles' > ,
        'masterid': '',
        'match_type': 0,
        'para_stage': 0,
        'para_reason': 0,
        'para_lose_client': False,
        'have_beard': False,
        'spell_mgr': < class 'gclient.gameplay.logic_base.spell.cspell_mgr.CSpellMgr' > ,
        'is_ads_status': 0,
        'is_shooting_status': 0,
        'is_drone_curing': False,
        'drone_curing_type': 0,
        'cure_drone_id': '',
        'drone_end_time': 0.0,
        'ban_skill': False,
        'info_chaos': False,
        'skill_relate_item': '',
        'pre_skill_relate_item': '',
        'skill_cast_entities': < class 'common.classutils.CustomListType' > ,
        'parkour': 0,
        'repel_bomb_explode_time': 0.0,
        'bomb_skins': < class 'common.classutils.CustomMapType' > ,
        'cure_gun_target': '',
        'buffs': < class 'gclient.gameplay.logic_base.entities.combatavatarmembers.cimp_combat_unit.Buffs' > ,
        'shadow_buffs': < class 'gclient.gameplay.logic_base.entities.combatavatarmembers.cimp_combat_unit.BuffsShadow' > ,
        'combat_team_id': '',
        'ai_attacker_id': '',
        'combat_data': < class 'gclient.gameplay.logic_base.entities.combatavatarmembers.cimp_combat_unit.CCombatData' > ,
        'final_kill_info': b '',
        'tmp_gun_kill_data': < class 'gclient.gameplay.logic_base.entities.combatavatarmembers.cimp_combat_unit.GunKillDataMap' > ,
        'card_background': 0,
        'national_flag': 1,
        'clan_name': '',
        'clan_icon': 0,
        'qualifying_score_dict': < class 'common.classutils.CustomMapType' > ,
        'show_qualifying_type': 1004,
        'suppression': < class 'common.classutils.CustomMapType' > ,
        'is_high_frequency': False,
        'server_hp': 100.0,
        'server_armor': 100.0,
        'maxarmor': 100.0,
        'extra_maxarmor': 0.0,
        'maxdhp': 100.0,
        'hero_id': 101,
        'combat_state': 0,
        'inner_combat_state': 0,
        'critical_spell': b '',
        'reborn_transform': < class 'common.classutils.CustomListType' > ,
        'debug_combat_options': < class 'common.classutils.CustomMapType' > ,
        'reborn_count': 0,
        'combat_attr': < class 'gshare.icombat_attr.ICombatAttr' > ,
        'faction': -1,
        'maxhp': 100.0,
        'arm_clothes': < class 'gclient.gameplay.logic_base.entities.combatavatarmembers.cimp_model.CArmClothes' > ,
        'client_buffs': < class 'gclient.gameplay.logic_base.entities.combatavatarmembers.cimp_client_buff.Buffs' > ,
        'rhs': < class 'gclient.gameplay.logic_base.entities.combatavatarmembers.cimp_replay.ClientReplayHandModelStatus' > ,
        'has_client': False,
        'uav_data': b '',
        'uav_data_full': b '',
        'is_block_gun_damage': False,
        'help_progress': 0.0,
        'target_help_progress': 0.0,
        'getting_help_state': 0,
        'helper_id': '',
        'is_helping': False,
        'helping_id': '',
        'start_get_help': 0.0,
        'help_self_speed': 20.0,
        'help_other_speed': 20.0,
        'disable_help_count': 0,
        'fps_mode': True,
        'speed_level': 0,
        'pose_type_server': 0,
        'pose_crouch': False,
        'motion_state': '',
        'standup_matid': 0,
        'is_in_swim': False,
        'motion_state_info': < class 'common.classutils.CustomMapType' > ,
        'relay_state_info': < class 'gclient.gameplay.logic_base.entities.combatavatarmembers.cimp_motion.RelayStateInfoMap' > ,
        'c_eid': 0,
        'kr_eid': 0,
        'vehicle_id': '',
        'vehicle_seat': -1,
        'is_lean_out': False,
        'coins': 0,
        'backpack': < class 'gclient.gameplay.logic_base.equips.citem.Backpack' > ,
        'backpack_no': 0,
        'cur_weapon_guid': '',
        'cur_spec_weapon_guid': '',
        'cur_lefthand_weapon_guid': '',
        'cur_weapon_guid_server': '',
        'cur_spec_weapon_guid_server': '',
        'cur_lefthand_weapon_guid_server': '',
        'trailing_skin_item_id': 0,
        'moving_platform_guid': '',
        'is_in_house': False,
        'in_house_name': '',
        'sticky_objects': < class 'gclient.gameplay.util.sticky_object_util.StickyObjects' > ,
        'execute_target': '',
        'execute_time': 0.0,
        'executor': '',
        'execute_item_id': 0,
        'holographic_robot_id': '',
        'cannon_id': '',
        'fire_wall_id': '',
        '_maxssp': 4.0,
        'ssp': 4.0,
        '_minssp': 0.5,
        'settle_data': b '',
        'dying_killer': '',
        'dead_killer': '',
        'disengage_jamming_time': 0.0,
        'weekly_free_hero_ids': < class 'common.classutils.CustomListType' > ,
        'active_item_snares': < class 'common.classutils.CustomMapType' > ,
        'support_items': < class 'gclient.gameplay.logic_base.entities.combatavatarmembers.cimp_store.CSupportItems' > ,
        'fast_buy_items': < class 'gclient.gameplay.logic_base.entities.combatavatarmembers.cimp_store.CDefineGoodsItems' > ,
        'change_weapon_stamp': 0,
        'change_spec_weapon_stamp': 0,
        'recommend_friend': '',
        'recommend_friend_type': 1,
        'alert_level': 0,
        'prey_id': '',
        'ghost_energy': 100.0,
        'stealth_degree': 0.0,
        'fresnel_degree': 0.0,
        'talent_slots': < class 'gclient.gameplay.logic_base.comps.comp_talent.CTalentSlots' > ,
        'talent_code_cd': < class 'gclient.gameplay.logic_base.comps.comp_talent.CTalentCodeCD' > ,
        'talent_sensing_info': < class 'common.classutils.CustomMapType' > ,
        'enemies_show_in_map': < class 'common.classutils.CustomMapType' > ,
        'tactical_energy': 0,
        'tactical_level': 0,
        'talent_codes': < class 'common.classutils.CustomListType' > ,
        'talent_code_source': < class 'gclient.gameplay.logic_base.comps.comp_talent.CTalentCodeSource' > ,
        'expose_enemies_pos': < class 'gclient.gameplay.logic_base.comps.comp_talent.KilledTeamInfo' > ,
        'talent_data': < class 'gclient.gameplay.logic_base.comps.comp_talent.CPlayerTalentData' > ,
        'bomb_mode': 1,
        'mark_responds': < class 'gclient.gameplay.logic_base.comps.comp_mark.CMarkRespond' > ,
        'respond_marks': < class 'gclient.gameplay.logic_base.comps.comp_mark.CRespondMarks' > ,
        'airdrop_pickup_history_reborn': < class 'gclient.gameplay.logic_base.comps.comp_mark.AirDropPickupHistoryReborn' >
    },
    '__property_flag__': {
        'name': 2,
        'show_name': 2,
        'anchor': 2,
        'cur_titles': 2,
        'masterid': 2,
        'match_type': 2,
        'para_stage': 2,
        'para_reason': 2,
        'para_lose_client': 2,
        'have_beard': 2,
        'spell_mgr': 2,
        'is_ads_status': 2,
        'is_shooting_status': 2,
        'is_drone_curing': 2,
        'drone_curing_type': 2,
        'cure_drone_id': 2,
        'drone_end_time': 2,
        'ban_skill': 2,
        'info_chaos': 2,
        'skill_relate_item': 2,
        'pre_skill_relate_item': 2,
        'skill_cast_entities': 2,
        'parkour': 2,
        'repel_bomb_explode_time': 2,
        'bomb_skins': 2,
        'cure_gun_target': 2,
        'buffs': 2,
        'shadow_buffs': 2,
        'combat_team_id': 2,
        'ai_attacker_id': 2,
        'combat_data': 2,
        'final_kill_info': 2,
        'tmp_gun_kill_data': 2,
        'card_background': 2,
        'national_flag': 2,
        'clan_name': 2,
        'clan_icon': 2,
        'qualifying_score_dict': 2,
        'show_qualifying_type': 2,
        'suppression': 4,
        'is_high_frequency': 4,
        'server_hp': 4,
        'server_armor': 4,
        'maxarmor': 4,
        'extra_maxarmor': 4,
        'maxdhp': 4,
        'hero_id': 4,
        'combat_state': 4,
        'inner_combat_state': 4,
        'critical_spell': 4,
        'reborn_transform': 4,
        'debug_combat_options': 2,
        'reborn_count': 2,
        'combat_attr': 4,
        'faction': 4,
        'maxhp': 4,
        'arm_clothes': 2,
        'client_buffs': 4,
        'rhs': 2,
        'has_client': 2,
        'uav_data': 2,
        'uav_data_full': 2,
        'is_block_gun_damage': 2,
        'help_progress': 2,
        'target_help_progress': 2,
        'getting_help_state': 2,
        'helper_id': 2,
        'is_helping': 2,
        'helping_id': 2,
        'start_get_help': 2,
        'help_self_speed': 2,
        'help_other_speed': 2,
        'disable_help_count': 2,
        'fps_mode': 2,
        'speed_level': 2,
        'pose_type_server': 2,
        'pose_crouch': 2,
        'motion_state': 2,
        'standup_matid': 2,
        'is_in_swim': 2,
        'motion_state_info': 2,
        'relay_state_info': 4,
        'c_eid': 2,
        'kr_eid': 2,
        'vehicle_id': 2,
        'vehicle_seat': 2,
        'is_lean_out': 2,
        'coins': 2,
        'backpack': 2,
        'backpack_no': 2,
        'cur_weapon_guid': 2,
        'cur_spec_weapon_guid': 2,
        'cur_lefthand_weapon_guid': 2,
        'cur_weapon_guid_server': 2,
        'cur_spec_weapon_guid_server': 2,
        'cur_lefthand_weapon_guid_server': 2,
        'trailing_skin_item_id': 2,
        'moving_platform_guid': 4,
        'is_in_house': 2,
        'in_house_name': 2,
        'sticky_objects': 2,
        'execute_target': 2,
        'execute_time': 2,
        'executor': 2,
        'execute_item_id': 4,
        'holographic_robot_id': 2,
        'cannon_id': 2,
        'fire_wall_id': 2,
        '_maxssp': 4,
        'ssp': 4,
        '_minssp': 4,
        'settle_data': 2,
        'dying_killer': 2,
        'dead_killer': 2,
        'disengage_jamming_time': 2,
        'weekly_free_hero_ids': 2,
        'active_item_snares': 2,
        'support_items': 2,
        'fast_buy_items': 2,
        'change_weapon_stamp': 2,
        'change_spec_weapon_stamp': 2,
        'recommend_friend': 2,
        'recommend_friend_type': 2,
        'alert_level': 2,
        'prey_id': 2,
        'ghost_energy': 4,
        'stealth_degree': 4,
        'fresnel_degree': 4,
        'talent_slots': 2,
        'talent_code_cd': 2,
        'talent_sensing_info': 2,
        'enemies_show_in_map': 2,
        'tactical_energy': 2,
        'tactical_level': 2,
        'talent_codes': 2,
        'talent_code_source': 2,
        'expose_enemies_pos': 2,
        'talent_data': 2,
        'bomb_mode': 2,
        'mark_responds': 2,
        'respond_marks': 2,
        'airdrop_pickup_history_reborn': 2
    },
    '__weakref__': None,
    '_assist_aim_ban_reason': 0,
    '_auto_mark_item_guid': None,
    '_auto_mark_item_timer': {},
    '_be_shoot_tech_effect_timer': None,
    '_cc_nearby_timer': None,
    '_cc_speaking_timer': None,
    '_close_cc_timer_map': {},
    '_combat_team': < CombatTeamEntity_ShootingRange(Z5siQjw2U1BjSI81) > ,
    '_crisis_aware_see_info': {},
    '_crisis_aware_ticker': None,
    '_delay_dual_shoot_reason': 0,
    '_delay_shoot_reason': 0,
    '_enter_house_count': 0,
    '_enter_house_name': '',
    '_enter_house_range_count': 0,
    '_enter_house_range_name': '',
    '_execute_event_id': None,
    '_execute_hide_ui_timer': None,
    '_execute_third_model': None,
    '_fps_mode': True,
    '_hall_team_shield_ids': {},
    '_high_sky_client_para_stage': None,
    '_holographic_mark_entities': {},
    '_house_range_head_cover': False,
    '_house_range_timer': None,
    '_is_ads': True,
    '_is_ammo_reloading': False,
    '_is_auto_sprint': False,
    '_is_auto_supersprint': False,
    '_is_cinematics': False,
    '_is_deactive': False,
    '_is_destroyed': False,
    '_is_dual_shooting': False,
    '_is_in_house': False,
    '_is_real_ads': True,
    '_is_shooting': False,
    '_is_sprint': False,
    '_is_super_sprint': False,
    '_kill_ridicule_timer': None,
    '_last_execute_begin_time': 0,
    '_last_execute_cancel_time': 0,
    '_last_house_enter_trigger_name': None,
    '_lean_out_check_valid_timer': None,
    '_move_action_speed': 1.0,
    '_open_close_parachute_time': 0,
    '_para_check_stuck_count': 0,
    '_para_check_stuck_pre_pos': None,
    '_para_check_stuck_timer': None,
    '_pose_type': 0,
    '_prone_check_index': 0,
    '_prone_check_name': None,
    '_rhs': {},
    '_sky_sound_id': None,
    '_sky_sound_playing_id': None,
    '_sound_scan_core_event': None,
    '_sound_tips_ban_reason': 0,
    '_space': < Space(Z5sh9jw2U1BjSHj9) > ,
    '_speak_eids': [],
    '_spell_result_cache': [],
    '_tick_timer': 0,
    '_timers': {
        -56: < bound method CombatAvatarMember.TickUpdateSoundCache of < PlayerCombatAvatarShootingRange(Z5siQjw2U1BjSI8w) >> ,
        -57: < bound method PlayerCombatAvatarMember.OnClientBuffTick of < PlayerCombatAvatarShootingRange(Z5siQjw2U1BjSI8w) >> ,
        -58: < bound method PlayerCombatAvatarMember.ScaleEffectTimer of < PlayerCombatAvatarShootingRange(Z5siQjw2U1BjSI8w) >> ,
        -59: < bound method PlayerCombatAvatarMember.ReplayOnUploadCamera of < PlayerCombatAvatarShootingRange(Z5siQjw2U1BjSI8w) >> ,
        -60: < bound method PlayerCombatAvatarMember.ReplayOnFpsVarianceTick of < PlayerCombatAvatarShootingRange(Z5siQjw2U1BjSI8w) >> ,
        -61: < bound method PlayerCombatAvatarMember.TickCalcDistance of < PlayerCombatAvatarShootingRange(Z5siQjw2U1BjSI8w) >> ,
        -81: < built - in method clear of dict object at 0x781c958cc0 > ,
        -93: < built - in method clear of dict object at 0x7803bc2480 > ,
        -103: < built - in method clear of dict object at 0x78040c8dc0 > ,
        -104: < built - in method clear of dict object at 0x78040c9700 >
    },
    '_try_enter_ads': False,
    'ads_mark_pos_avatars': [],
    'ads_shield_effect': None,
    'ads_shield_timer': None,
    'aiming_enemy_id': '',
    'airdrop_store_near': set(),
    'ammos_for_cur_guns': {
        8,
        7
    },
    'anti_penetrate_draw_paths': [],
    'area': < area object at 0x7803705a40 > ,
    'armor': 50.0,
    'armor_effect': None,
    'armor_recovering': False,
    'assassinate_effect_id': None,
    'assist_aim_cls': {
        5: < class 'gclient.framework.util.assist_aim_util.AssistAimMelee' > ,
        20: < class 'gclient.framework.util.assist_aim_util.AssistAimTracingTargetNoSearching' > ,
        21: < class 'gclient.framework.util.assist_aim_util.AssistAimAndShootTracingNoSearching' >
    },
    'assist_aims': {
        5: < gclient.framework.util.assist_aim_util.AssistAimMelee object at 0x780371ac10 > ,
        20: < gclient.framework.util.assist_aim_util.AssistAimTracingTargetNoSearching object at 0x7804058650 > ,
        21: < gclient.framework.util.assist_aim_util.AssistAimAndShootTracingNoSearching object at 0x7804059590 >
    },
    'assist_mark': < gclient.framework.util.assist_aim_util.AssistMark object at 0x780371a9d0 > ,
    'attach_model_dict': {},
    'auto_pickup_delay': False,
    'auto_send_interval_duration': 0.0,
    'auto_send_interval_last_pos': (0, 0, 0),
    'auto_send_interval_last_yaw': 0.0,
    'auto_sprint_timer': None,
    'ballistic_effect_history': defaultdict( < class 'float' > , {}),
    'base_armor': 50.0,
    'base_maxarmor': 50.0,
    'before_swim_weapon_guid': '',
    'block_need_slow_down': True,
    'bomb_contact_entity': None,
    'bomb_path_effect': None,
    'break_use_medicine': False,
    'broadcast_sound_interval': 0.25,
    'broadcast_sound_limiter': defaultdict( < class 'float' > , {}),
    'buff_camera_effect_tmp': {},
    'cache_enter_trigger_items': {},
    'calc_distance_diff_timer': -61,
    'camera_date_getters': {
        0: < bound method PlayerCombatAvatarMember._GetCameraData_TPS of < PlayerCombatAvatarShootingRange(Z5siQjw2U1BjSI8w) >> ,
        1: < bound method PlayerCombatAvatarMember._GetCameraData_FPS of < PlayerCombatAvatarShootingRange(Z5siQjw2U1BjSI8w) >> ,
        2: < bound method PlayerCombatAvatarMember._GetCameraData_TPS of < PlayerCombatAvatarShootingRange(Z5siQjw2U1BjSI8w) >> ,
        3: < bound method PlayerCombatAvatarMember._GetCameraData_AIM of < PlayerCombatAvatarShootingRange(Z5siQjw2U1BjSI8w) >> ,
        4: < bound method PlayerCombatAvatarMember._GetCameraData_DEATH of < PlayerCombatAvatarShootingRange(Z5siQjw2U1BjSI8w) >> ,
        5: < bound method PlayerCombatAvatarMember._GetCameraData_FREE of < PlayerCombatAvatarShootingRange(Z5siQjw2U1BjSI8w) >> ,
        6: < bound method PlayerCombatAvatarMember._GetCameraData_CamCtrl of < PlayerCombatAvatarShootingRange(Z5siQjw2U1BjSI8w) >> ,
        7: < bound method PlayerCombatAvatarMember._GetCameraData_Emote of < PlayerCombatAvatarShootingRange(Z5siQjw2U1BjSI8w) >> ,
        8: < bound method PlayerCombatAvatarMember._GetCameraData_TPS of < PlayerCombatAvatarShootingRange(Z5siQjw2U1BjSI8w) >>
    },
    'camera_effect_ids': {},
    'camera_effect_timers': {},
    'camera_id_before_ads': None,
    'can_high_sky_para': False,
    'can_para_after_samurai_sprint': False,
    'can_shoot_player_for_sound': False,
    'cannon_entity': None,
    'cannon_pre_place_effect': None,
    'cc_speak_channel': 0,
    'cc_voice_channel': 0,
    'check_aim_enemy_interval': 0.2,
    'check_aim_enemy_ref': 0,
    'check_aim_enemy_timer': None,
    'check_door_trigger': None,
    'check_item_timer': None,
    'check_swim_state_timer': None,
    'client_ammo_update_timer': None,
    'client_buff_ticker': -57,
    'client_left_ammo_update_timer': None,
    'client_parkour': 0,
    'client_spectator_camera_stream': [],
    'cold_fields': {},
    'combat_log_dict': {
        'CombatGunFireLog': {}
    },
    'combat_status_timestamps': {},
    'combat_team': < CombatTeamEntity_ShootingRange(Z5siQjw2U1BjSI81) > ,
    'common_center_mark_dict': {},
    'common_mark_dict': {
        'Z5sjNEIaqXd2RUYA': < gclient.framework.commoncomps.common_toplogo.ToplogoGunRefit object at 0x7803b32910 >
    },
    'common_mark_info': {
        'Z5sjNEIaqXd2RUYA': {
            'camera_hit_min_opacity': 70,
            'offset': (1, 2.5, 0),
            'cls': 'ToplogoGunRefit',
            'visible_distance': 50.0,
            'camera_hit_max_dis': 165,
            'camera_hit_max_opacity': 255,
            'min_opacity': 1.0,
            'id': 10,
            'camera_hit': False,
            'icon': 733,
            'max_opacity': 1.0,
            'camera_hit_min_dis': 50,
            'fov_distance': 10.0,
            'pos': (-23.85, 0, -6.73),
            'scene_on': True
        }
    },
    'container_show_set': set(),
    'controlled_target_id': None,
    'controller_sensitivity_x': 0.0018581232,
    'controller_sensitivity_y': 0.0018581232,
    'controlling_drone': None,
    'controlling_drone_id': None,
    'controlling_target': None,
    'cur_active_world_field_id': 6,
    'cur_focus_box_guid': None,
    'cur_focus_item': None,
    'cur_focus_item_pos': None,
    'cur_item_guid': '',
    'cur_mark_avt_id': None,
    'cur_mark_mission_guid': '',
    'cur_maxhp': 125.0,
    'cur_sel_emote': -1,
    'cur_sel_medicine_item_guid': None,
    'cur_sel_throwable_item_guid': None,
    'cur_shield_magic_field_id': None,
    'cur_target_execute_id': None,
    'cure_connect_line_effect_info': None,
    'cure_uav_camera_effect': None,
    'cure_uav_effect': None,
    'degree_fps_floor': 5.0,
    'degree_fps_upper': 25.0,
    'delay_check_weapon_timer': None,
    'delay_emote_timer': None,
    'delay_switch_weapon': 0,
    'design_combat_properties': {
        'suppression_decay': 1,
        'full_slide_interval': 0.65,
        'break_armor_recover_time': 7.4,
        'hipfire_revealname_yawangle': 50.0,
        'rescue_recovertime': 7.0,
        'incomplete_slide_factor': 0.9,
        'max_health': 125,
        'laydown_health': 225,
        'lie_interval': 0.4,
        'rescue_health': 30,
        'laydown_dot': 4.0,
        'moving_hipfire_spread_ratio': (0, 0, 0.1, 0.15, 0.15, 0.15),
        'pick_tactical_energy': {
            1: 50,
            2: 100,
            3: 200,
            4: 300,
            5: 400,
            6: 500
        },
        'jump_y_Vec2': 4.0,
        'max_armor': 0,
        'suppression_max': 20,
        'armor_recover_time': 6.6,
        'movespeed_correction': 0.0,
        'crouch_interval': 0.4,
        'ads_revealname_yawangle': 40.0,
        'moving_dist_ratio': (0, 0, 0.1, 0.15, 0.15, 0.15),
        'shortest_revealtime': 0.75,
        'armor_recover_value': 20.0,
        'recover_time': 7.0,
        'other_progress_loss_speed': 20.0,
        'help_self_speed': 15.0,
        'pose_dist_ratio': (0, -0.3, 0.2, 0.2, -0.5),
        'jump_y_Vec1': 5.5,
        'recover_value': 0.0,
        'rescue_armor_recover_time': 4.5,
        'ads_revealname_pitchangle': 20.0,
        'self_progress_loss_speed': 15.0,
        'pose_hipfire_spread_ratio': (0, -0.05, 0.2, 0.2, -0.5),
        'slide_interval': 0.8,
        'hipfire_revealname_pitchangle': 20.0,
        'enter_prone_time': 1.0,
        'id': 0,
        'shortest_displaytime': 1.0,
        'suicide_time': 5.0,
        'help_other_speed': 15.0,
        'supersprint_interval': 1.5,
        'supersprint_recover': 0.5,
        'tactical_core_lv': {
            1: 300,
            2: 500,
            3: 750,
            4: 1000,
            5: 1250
        },
        'supersprint_time': 3.0,
        'jump_interval': 0.4
    },
    'detached_from_vehicle': True,
    'dir': (0.4486425817012787, 0.0, 0.0),
    'disable_signal': {
        32,
        3,
        6,
        7,
        8,
        16,
        54,
        23,
        25
    },
    'distance_crouch2': 0,
    'distance_fps_floor': 5.0,
    'distance_fps_max_dist': 125.0,
    'distance_fps_upper': 35.0,
    'distance_from_camera': 0.0,
    'distance_vehicle': 17.952216285326806,
    'distance_walk': 0,
    'door_building_owner_map': {},
    'drone_init_pos': None,
    'dual_gun_fire_timestamp': 0,
    'dual_shoot_immediately': True,
    'dual_shoot_rescue_timer': None,
    'electical_proto': None,
    'emitter_obstruct': 0,
    'emote_cancel_range': 10000,
    'emote_detect_timer': None,
    'emote_hide_targets': [],
    'emote_log_dict': {},
    'emote_sel_rid': 0,
    'enable_slope': True,
    'execute_dissolving_entities': [],
    'execute_player_pre_pos': None,
    'exit_slide_timestamp': 0,
    'expose_killed_enemy_pos_timer': None,
    'extra_armor': 0.0,
    'extra_armor_effect': None,
    'extra_max_armor_effect': None,
    'feel_hp_timer': None,
    'feel_surmount1_id': '',
    'feel_surmount1_stamp': 1738220339.9899697,
    'feel_surmount1_timer': None,
    'fire_by_left_timestamp': 0,
    'fire_by_right_timestamp': 0,
    'fireend_by_left_timestamp': 0,
    'fireend_by_right_timestamp': 0,
    'firewall_mode': 0,
    'follow_entity': None,
    'forbid_auto_pickup_time_map': {
        'all': 0.0
    },
    'force_cure_self': False,
    'force_no_fall_hurt': False,
    'force_use_client_pos': False,
    'freefall_start_height': -100,
    'fsm_ads_mark_pos': None,
    'fsm_auto_fire': None,
    'fsm_auto_fire_timer': None,
    'game_logic': < GameLogicShootingRange(Z5sh9jw2U1BjSHj + ) > ,
    'give_up_timer': None,
    'gun_fire_timestamp': 0,
    'gun_spell_last_mark_enemy': None,
    'gun_spell_mark_enemy_stamp': None,
    'gyroscope': < gclient.framework.util.gyroscope.GyroscopePoseCombat object at 0x78037f1b90 > ,
    'gyroscope_horizontal_reverse': 0,
    'gyroscope_input_cut_off': 0.05,
    'gyroscope_mode': 1,
    'gyroscope_sens_by_state': 2.0,
    'gyroscope_switch_mode': 1,
    'gyroscope_vertical_reverse': 0,
    'hand_model': < gclient.gameplay.logic_base.models.hand_model.HandModel object at 0x7803718050 > ,
    'hand_model_id': 229,
    'hand_model_status_cache': {},
    'hand_model_status_hits': 0,
    'hand_model_status_last': '',
    'hand_model_status_statistic': defaultdict( < class 'int' > , {}),
    'hand_model_status_total': 0,
    'handmodel_status': {},
    'has_recommend_item': False,
    'heartbeat_avatar_cache_info': {},
    'heartbeat_delay_start_timer': None,
    'heartbeat_end_timer': None,
    'heartbeat_endtime': None,
    'heartbeat_num': 0,
    'heartbeat_reset_timer': None,
    'heartbeat_spell_state': 0,
    'heartbeat_start_timer': None,
    'hero_skill_talent': [3000, 3001],
    'hero_skin_effects': [],
    'highlight_around_items_timer': None,
    'highlight_item_guids': set(),
    'hold_effect_id': None,
    'hold_item_timer': None,
    'hp': 125.0,
    'id': 'Z5siQjw2U1BjSI8w',
    'ig_voice_mgr': < gclient.gameplay.util.ig_voice_manager.IgVoiceManager object at 0x7803719850 > ,
    'in_same_house_with_player': True,
    'inspection_timer': None,
    'invalid_trans': << 1.0000,
    0.0000,
    0.0000 > < 0.0000,
    1.0000,
    0.0000 > < 0.0000,
    -0.0000,
    1.0000 > < 0.0000,
    -2000.0000,
    0.0000 >> ,
    'is_ads': True,
    'is_alive': True,
    'is_alive_state': True,
    'is_ammo_reloading': False,
    'is_auto_sprint': False,
    'is_auto_supersprint': False,
    'is_ban_sprint': False,
    'is_dead_state': False,
    'is_drone_connect_loading_finished': True,
    'is_dual_shooting': False,
    'is_dying_state': False,
    'is_enter_ads_by_fire': False,
    'is_fast_raise_weapon': True,
    'is_fire_by_left': False,
    'is_fire_by_right': False,
    'is_fire_manually': False,
    'is_fps_avatar': True,
    'is_fps_mode': 1,
    'is_gyroscope_reverse': True,
    'is_help_by_uav': False,
    'is_in_air': False,
    'is_invincible': False,
    'is_knocking': False,
    'is_on_sky': False,
    'is_player_set_camera': False,
    'is_real_ads': True,
    'is_refuse_team_mark': False,
    'is_replay_avatar': False,
    'is_replay_room': False,
    'is_replaying': False,
    'is_selecting_medicine': False,
    'is_selecting_throwable': False,
    'is_shoot_breaking': False,
    'is_shooting': 0,
    'is_slide_to_end': False,
    'is_sprint': False,
    'is_super_sprint': False,
    'is_unfold_container': False,
    'is_unfold_main_pickup': True,
    'is_using_nova_second_skill': False,
    'is_vehicle_driver': False,
    'is_vehicle_passenger': False,
    'item_fsms': {},
    'jump_begin_time': 0,
    'jump_top_height': -100,
    'last_ask_help_time': 0,
    'last_camera_frame': [430, -94, 896, 0, 5000, 4000, 0, 0],
    'last_creep_up_timestamp': 0,
    'last_crouch2_position': None,
    'last_crouch_timestamp': 0,
    'last_jump_timestamp': 1738220340.382635,
    'last_move_dir': 1,
    'last_position': (-16.621000289916992, 0.04200005531311035, -6.783999919891357),
    'last_prone_timestamp': 0,
    'last_server_count': 0,
    'last_server_pos_stamp': 0,
    'last_server_pos_time': 0,
    'last_server_position': None,
    'last_shoot_idx': -1,
    'last_slide_timestamp': 0,
    'last_speed_level': 1,
    'last_support_item_id': '',
    'last_weapon_guid': '',
    'light_attack_mode': False,
    'light_attack_pos': None,
    'light_attack_range_eid': None,
    'logger': < Logger PlayerCombatAvatarShootingRange(DEBUG) > ,
    'low_fps_check': < gclient.framework.util.low_fps_util.LowFpsCheck object at 0x7803719910 > ,
    'low_hp_effect_timer': None,
    'magic_bullet_lock_target': None,
    'magic_bullet_shoot_miss_count': 0,
    'main_spell': 1,
    'mark_effect_dict': {},
    'mark_toplogo_dict': {},
    'mark_toplogo_hit_guid': '',
    'mark_toplogo_hit_type': 1,
    'mark_toplogo_op_mode': 0,
    'master': < PlayerAvatar(A + pUrwUSaBFTuCIK) > ,
    'maxssp': 3.0,
    'med_last_offset_y': 0,
    'med_sel_rid': 0,
    'medicine_timer': None,
    'minssp': 1.5,
    'missile_entity': None,
    'missile_indicate_effect_id': None,
    'missile_indicate_pos': None,
    'missile_indicate_tick': None,
    'model': < gclient.gameplay.logic_base.models.avatar_model.PlayerAvatarModel object at 0x7803718850 > ,
    'model_loaded': True,
    'move_action_speed': 1.0,
    'move_dir': 0,
    'nearby_combat_items': set(),
    'nearby_dying_enemies': [],
    'next_lefthand_weapon_guid': '',
    'next_spec_weapon_guid': '',
    'next_weapon_guid': '',
    'path_queryer': {},
    'pc_pick_mgr': None,
    'personal_store_data': None,
    'pick_up_box_timer': None,
    'pickup_group_box_ids': [],
    'pickup_item_ticker': None,
    'place_entity': None,
    'place_entity_guid': None,
    'place_entity_rotate': 0,
    'place_explode_entity': None,
    'place_firewall_effects': [],
    'place_paranoia_guids': [],
    'pos': (-16.4495792388916, 0.05000007525086403, -7.268758296966553),
    'pose_type': 0,
    'position': (-16.4495792388916, 0.05000007525086403, -7.268758296966553),
    'pre_weapon_slot': 1001,
    'previous_controller_sensitivity_x': 0.0024,
    'previous_controller_sensitivity_y': 0.0024,
    'previous_sensitivity_x': 0.004,
    'previous_sensitivity_y': 0.004,
    'prone_end_for_crouch': False,
    'prone_for_forbidden_ads': False,
    'prone_is_ads': False,
    'prone_slope_timer': None,
    'rage_model_effect_id': None,
    'recon_drone_frame_top_logo': None,
    'recon_drone_mark_ent_ids': set(),
    'red_pack_msg': [],
    'refresh_observe_timer': None,
    'reload_dual_fire_interval_timer': None,
    'reload_fire_interval_timer': None,
    'replay_assist_inputs_stamp': 1738220339.9899285,
    'replay_camera_expired': 0.0,
    'replay_camera_stamp': 1738220343.511303,
    'replay_camera_stream': [],
    'replay_fps_variance_timer': -60,
    'replay_last_valid_pos': (-16.4495792388916, 0.05000007525086403, -7.268758296966553),
    'replay_on_upload_camera_timer': -59,
    'replay_rpc_stream': [],
    'replay_upload_assist_timer': None,
    'replay_upload_camera_interval': 0.02177576906979084,
    'samurai_sprint_effect_id': 0,
    'samurai_sprint_pos': None,
    'samurai_sprint_start_time': 0,
    'samurai_sprint_tick': 0,
    'scale_effect_timer': -58,
    'scale_effects': {},
    'scan_score_timer': None,
    'scaned_talent_item': None,
    'send_ig_request_chat_cd': 1738220339.9895895,
    'send_ig_request_chat_count': 0,
    'send_ig_request_chat_support_cd': 1738220339.9895935,
    'send_ig_request_chat_support_count': 0,
    'sens_factor': 1.0,
    'sensitivity_factor': 5e-05,
    'sensitivity_lerp_duration': 0,
    'sensitivity_lerp_elapsed': 0,
    'sensitivity_x': 0.003096872,
    'sensitivity_y': 0.003096872,
    'server': < client.AsioServerProxy.AsioServerProxy object at 0x7803544650 > ,
    'sfx_cache_max_gun_dist': 125,
    'shoot_idx': 0,
    'shoot_immediately': True,
    'shoot_rescue_timer': None,
    'show_game_sound': False,
    'skill_weapon_down_time': 0,
    'sky_fade_time_zero': False,
    'sky_process_timer': None,
    'sky_render_switcher': None,
    'smart_f_funcs': [( < bound method PlayerCombatAvatarMember.GetSmartFPos_PickUp of < PlayerCombatAvatarShootingRange(Z5siQjw2U1BjSI8w) >> , < bound method PlayerCombatAvatarMember.DoSmartF_PickUp_Down of < PlayerCombatAvatarShootingRange(Z5siQjw2U1BjSI8w) >> , < bound method PlayerCombatAvatarMember.DoSmartF_PickUp_Up of < PlayerCombatAvatarShootingRange(Z5siQjw2U1BjSI8w) >> ), ( < bound method PlayerCombatAvatarMember.GetSmartFPos_InteractiveUIAction of < PlayerCombatAvatarShootingRange(Z5siQjw2U1BjSI8w) >> , < bound method PlayerCombatAvatarMember.DoSmartF_InteractiveUIAction_Down of < PlayerCombatAvatarShootingRange(Z5siQjw2U1BjSI8w) >> , < bound method PlayerCombatAvatarMember.DoSmartF_InteractiveUIAction_Up of < PlayerCombatAvatarShootingRange(Z5siQjw2U1BjSI8w) >> )],
    'snare_dict': {},
    'sound_cache_gun_direction': < 0.4771,
    -0.0000,
    0.9911 > ,
    'sound_cache_gun_param_dict': {
        'roof_obstruct': 1,
        'in_same_room': 1
    },
    'sound_cache_gun_sound_media': 'm4a1_media',
    'sound_cache_is_compound_bow': False,
    'sound_cache_is_friend': True,
    'sound_cache_is_own_gun': True,
    'sound_cache_is_slient': 0.0,
    'sound_cache_max_gun_dist': 125,
    'sound_dict': {
        6: 5,
        4: 12
    },
    'sound_tag_dict': defaultdict( < class 'list' > , {
        'AdsUp': [(4, 12)]
    }),
    'space': < Space(Z5sh9jw2U1BjSHj9) > ,
    'space_snare_update_cache': None,
    'speak_eids': [],
    'speed': 5.5,
    'speed_level_prop': 0,
    'sprint_begin_time': 0,
    'sprint_door': None,
    'sprint_rb': None,
    'ssp_recover_speed': 0.1,
    'ssp_use_speed': 0.2,
    'standup_mat_id': 0,
    'state_relationship_cache': {
        (12, ('Idle', )): (3, None),
        (19, ('Idle', )): (3, None)
    },
    'state_relationship_set': {
        'EnterAds',
        'Idle'
    },
    'story_tick_funcs': [ < bound method PlayerCombatAvatarMember.UpdateInvisibleAvatarsFrameLimit of < PlayerCombatAvatarShootingRange(Z5siQjw2U1BjSI8w) >> , < bound method PlayerCombatAvatarMember.TickDealSpellResultRpc of < PlayerCombatAvatarShootingRange(Z5siQjw2U1BjSI8w) >> , < bound method PlayerCombatAvatarMember.ReplayOnPackTick of < PlayerCombatAvatarShootingRange(Z5siQjw2U1BjSI8w) >> , < bound method PlayerCombatAvatarMember.RaycastForMovingPlatform of < PlayerCombatAvatarShootingRange(Z5siQjw2U1BjSI8w) >> , < bound method GyroscopePoseCombat.GyroscopeTick of < gclient.framework.util.gyroscope.GyroscopePoseCombat object at 0x78037f1b90 >> ],
    'super_sprint_duration': 0.0,
    'supply_dict': {},
    'switch_dict_cache': {
        6: {
            'expired': 1738220340.9891925,
            'switch_dict': {
                'visual': 'first',
                'gun_type': 'm4a1'
            }
        },
        4: {
            'expired': 1738220343.2865322,
            'switch_dict': {
                'visual': 'first',
                'gun_type': 'm4a1'
            }
        }
    },
    'switch_dict_cache_timeout': 0.5,
    'sync_sound_dict': {},
    'talent_exp_proto': {},
    'target_controller_sensitivity_x': 0.0018581232,
    'target_controller_sensitivity_y': 0.0018581232,
    'target_sensitivity_x': 0.003096872,
    'target_sensitivity_y': 0.003096872,
    'target_trigger_entity': None,
    'team_val_recon_drone_id': None,
    'teammate_backpack_usages': defaultdict( < class 'dict' > , {}),
    'teammate_info': CCombatTeamMembers_ShootingRange({
        'Z5siQjw2U1BjSI8w': CCombatTeamMember_ShootingRange({
            'head_url': '',
            'extra_maxarmor': 0.0,
            'maxarmor': 50.0,
            'maxhp': 125.0,
            'hp': 125.0,
            'armor': 50.0,
            'is_leave': 0,
            'is_alive': 1,
            'official_head': 6030000040,
            'gender': 0,
            'head_frame': 0,
            'name': 'AllysoC29727',
            'show_id': '588166894644',
            'display_item_id': 6120000010,
            'yaw': 0.4477691054344177,
            'extra': CustomMapType({}),
            'show_name': 'AllysoC29727',
            'tactical_level': 1,
            'backpack_public': 1,
            'hall_backpacks': [],
            'hall_melee_info': [],
            'client_loaded': 1,
            'select_hero_id': 101,
            'settle_be_liked_map': SettleBeLikedMap({}),
            'is_foil_man': 0,
            'anchor': 0,
            'cur_titles': [],
            'elo': 0,
            'id': 'Z5siQjw2U1BjSI8w',
            'arm_clothes': CustomMapType({
                300: 3000000010
            }),
            'para_stage': 0,
            'masterid': 'A+pUrwUSaBFTuCIK',
            'mark': Mark_Moba({}),
            'pre_select_hero_id': 0,
            'level': 1,
            'c_eid': 0,
            'hall_team_guid': '',
            'para_reason': 0,
            'cc_mtf': 0,
            'slot': 1,
            'settle_be_liked': [],
            'p': b '\xf0\xff\x00\x00\xf9\xff'
        })
    }),
    'teammate_xray_hidden_reason': 0,
    'tell_server_motion_state': 'Idle',
    'throw_item': None,
    'throw_item_guid': '',
    'throwable_last_offset_y': 0,
    'throwable_sel_rid': 0,
    'throwable_timer': None,
    'tmp_forbidden_create_bomb_effect': False,
    'toplogo_not_in_hide_state_enemy': set(),
    'total_pickup_data': {
        'nearby': {
            'id': 'nearby',
            'title': 'Nearby',
            'data': [],
            'priority': 0,
            'item_entity': None
        }
    },
    'total_pickup_data_pc_check': {},
    'total_pickup_data_sort': [{
        'id': 'nearby',
        'title': 'Nearby',
        'data': [],
        'priority': 0,
        'item_entity': None
    }],
    'total_pickup_item': {},
    'total_reset_sensor_times': 0,
    'tps_show_entities': [],
    'trainee_info': [],
    'trainer_info': '',
    'trigger_inner_ids': [],
    'trigger_items_timer': 0,
    'trigger_supply_auto_open_timer': None,
    'trigger_vehicle_counts': {},
    'try_dual_fire_start': False,
    'try_enter_ads': False,
    'try_fire_start': False,
    'uav_start_time': None,
    'unit_model_id': 87,
    'update_around_items_timer': None,
    'use_camera_fps_for_para': True,
    'valid_trigger_entity_list': [],
    'vehicle': None,
    'vice_spell': None,
    'wait_f_up_func': None,
    'waiting_pickup_count_map': {},
    'wallbomb_mode': 0,
    'watch_entity': 'undefined',
    'water_height': -150,
    'water_trigger_id_list': [],
    'weapon_attr_cache': {},
    'weapon_guid_before_dying': '',
    'window_height_2': 540.0,
    'window_width_2': 1200.0,
    'world_fields': [(6, 'Z5siQjw2U1BjSI8w')],
    'xdroid_buy_callback': None,
    'yaw': 0.4487450913683175
}